-- =============================================================================
-- PROJETO: PETTRACK - SISTEMA DE MONITORAMENTO E SAÚDE ANIMAL
-- DISCIPLINA: Mastering Relational and Non-Relational Database
-- INSTITUIÇÃO: FIAP - Challenge 2026 (2º Ano ADS - Turma 2TDSPF)
-- INTEGRANTES:
--   - Gabriel Sbrana Campos     - RM 565849
--   - Moises Waidemann          - RM 563719
--   - Thiago Rodrigues da Mota  - RM 563765
--   - Richard Freitas           - RM 566127
--
-- VERSÃO CORRIGIDA: ajustes de integridade referencial na carga de dados
-- e inclusão de todos os objetos do 2º Semestre (Sprint 3)
-- =============================================================================

-- =============================================================================
-- 1. LIMPEZA DO AMBIENTE (DROP TABLES E SEQUENCES)
-- Garante a recriação limpa do schema, eliminando restrições em cascata.
-- =============================================================================

DROP TABLE TB_ADESAO_MEDICAMENTO CASCADE CONSTRAINTS;
DROP TABLE TB_ALERTA CASCADE CONSTRAINTS;
DROP TABLE TB_BCS_HISTORICO CASCADE CONSTRAINTS;
DROP TABLE TB_COLLAR_LEITURA CASCADE CONSTRAINTS;
DROP TABLE TB_SCORE_HISTORICO CASCADE CONSTRAINTS;
DROP TABLE TB_NOTIFICACAO CASCADE CONSTRAINTS;
DROP TABLE TB_PROTOCOLO_PREVENTIVO CASCADE CONSTRAINTS;
DROP TABLE TB_MEDICAMENTO CASCADE CONSTRAINTS;
DROP TABLE TB_EVENTO_CLINICO CASCADE CONSTRAINTS;
DROP TABLE TB_PET CASCADE CONSTRAINTS;
DROP TABLE TB_CLINICA CASCADE CONSTRAINTS;
DROP TABLE TB_TUTOR CASCADE CONSTRAINTS;
DROP TABLE TB_LOG_ERRO CASCADE CONSTRAINTS;
DROP TABLE TB_AUDITORIA_PETTRACK CASCADE CONSTRAINTS;

-- Remoção dos geradores de chaves primárias
DROP SEQUENCE SEQ_TUTOR;
DROP SEQUENCE SEQ_CLINICA;
DROP SEQUENCE SEQ_PET;
DROP SEQUENCE SEQ_EVENTO_CLINICO;
DROP SEQUENCE SEQ_PROTOCOLO;
DROP SEQUENCE SEQ_MEDICAMENTO;
DROP SEQUENCE SEQ_ADESAO;
DROP SEQUENCE SEQ_NOTIFICACAO;
DROP SEQUENCE SEQ_SCORE_HIST;
DROP SEQUENCE SEQ_BCS_HIST;
DROP SEQUENCE SEQ_COLLAR;
DROP SEQUENCE SEQ_ALERTA;
DROP SEQUENCE SEQ_LOG_ERRO;
DROP SEQUENCE SEQ_AUDITORIA;

-- =============================================================================
-- 2. CRIAÇÃO DE SEQUENCES
-- =============================================================================
CREATE SEQUENCE SEQ_TUTOR          START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_CLINICA        START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_PET            START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_EVENTO_CLINICO START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_PROTOCOLO      START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_MEDICAMENTO    START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_ADESAO         START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_NOTIFICACAO    START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_SCORE_HIST     START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_BCS_HIST       START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_COLLAR         START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_ALERTA         START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_LOG_ERRO       START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_AUDITORIA      START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

-- =============================================================================
-- 3. CRIAÇÃO DAS TABELAS (DDL)
-- =============================================================================

CREATE TABLE TB_LOG_ERRO (
    ID_LOG        NUMBER         NOT NULL,
    NM_PROCEDURE  VARCHAR2(100)  NOT NULL,
    NM_USUARIO    VARCHAR2(100)  NOT NULL,
    DT_OCORRENCIA DATE           DEFAULT SYSDATE NOT NULL,
    CD_ERRO       NUMBER         NOT NULL,
    DS_MENSAGEM   VARCHAR2(4000),
    CONSTRAINT TB_LOG_ERRO_PK PRIMARY KEY (ID_LOG)
);

CREATE TABLE TB_TUTOR (
    ID_TUTOR    NUMBER         NOT NULL,
    NM_TUTOR    VARCHAR2(150)  NOT NULL,
    DS_EMAIL    VARCHAR2(200)  NOT NULL,
    NR_TELEFONE VARCHAR2(20),
    DS_ENDERECO VARCHAR2(300),
    DT_CADASTRO DATE           DEFAULT SYSDATE NOT NULL,
    CONSTRAINT TB_TUTOR_PK       PRIMARY KEY (ID_TUTOR),
    CONSTRAINT TB_TUTOR_EMAIL_UN UNIQUE      (DS_EMAIL)
);

CREATE TABLE TB_CLINICA (
    ID_CLINICA  NUMBER         NOT NULL,
    NM_CLINICA  VARCHAR2(200)  NOT NULL,
    NR_CNPJ     VARCHAR2(18)   NOT NULL,
    DS_EMAIL    VARCHAR2(200),
    NR_TELEFONE VARCHAR2(20),
    DS_ENDERECO VARCHAR2(300),
    DT_CADASTRO DATE           DEFAULT SYSDATE NOT NULL,
    CONSTRAINT TB_CLINICA_PK      PRIMARY KEY (ID_CLINICA),
    CONSTRAINT TB_CLINICA_CNPJ_UN UNIQUE      (NR_CNPJ)
);

CREATE TABLE TB_PET (
    ID_PET        NUMBER        NOT NULL,
    NM_PET        VARCHAR2(100) NOT NULL,
    DS_ESPECIE    VARCHAR2(50)  NOT NULL,
    DS_RACA       VARCHAR2(100),
    DS_SEXO       CHAR(1),
    NR_IDADE_ANOS NUMBER(3,1),
    NR_PESO_KG    NUMBER(6,3),
    DT_CADASTRO   DATE          DEFAULT SYSDATE NOT NULL,
    ID_TUTOR      NUMBER        NOT NULL,
    ID_CLINICA    NUMBER        NOT NULL,
    CONSTRAINT TB_PET_PK      PRIMARY KEY (ID_PET),
    CONSTRAINT CK_PET_SEXO    CHECK (DS_SEXO IN ('F','M')),
    CONSTRAINT FK_PET_TUTOR   FOREIGN KEY (ID_TUTOR)   REFERENCES TB_TUTOR  (ID_TUTOR),
    CONSTRAINT FK_PET_CLINICA FOREIGN KEY (ID_CLINICA) REFERENCES TB_CLINICA (ID_CLINICA)
);

CREATE TABLE TB_EVENTO_CLINICO (
    ID_EVENTO      NUMBER         NOT NULL,
    TP_EVENTO      VARCHAR2(50)   NOT NULL,
    DT_EVENTO      DATE           NOT NULL,
    DS_DIAGNOSTICO VARCHAR2(1000),
    DS_OBSERVACAO  VARCHAR2(2000),
    ID_PET         NUMBER         NOT NULL,
    ID_CLINICA     NUMBER         NOT NULL,
    CONSTRAINT TB_EVENTO_CLINICO_PK PRIMARY KEY (ID_EVENTO),
    CONSTRAINT CK_EVENTO_TIPO       CHECK (TP_EVENTO IN ('CIRURGIA','CONSULTA','EXAME','RETORNO')),
    CONSTRAINT FK_EVENTO_PET        FOREIGN KEY (ID_PET)     REFERENCES TB_PET    (ID_PET),
    CONSTRAINT FK_EVENTO_CLINICA    FOREIGN KEY (ID_CLINICA) REFERENCES TB_CLINICA (ID_CLINICA)
);

CREATE TABLE TB_PROTOCOLO_PREVENTIVO (
    ID_PROTOCOLO NUMBER        NOT NULL,
    TP_PROTOCOLO VARCHAR2(50)  NOT NULL,
    NM_PROTOCOLO VARCHAR2(200) NOT NULL,
    DT_APLICACAO DATE,
    DT_PROXIMA   DATE,
    ST_STATUS    VARCHAR2(20)  NOT NULL,
    ID_PET       NUMBER        NOT NULL,
    CONSTRAINT TB_PROTOCOLO_PREVENTIVO_PK PRIMARY KEY (ID_PROTOCOLO),
    CONSTRAINT CK_PROT_TIPO               CHECK (TP_PROTOCOLO IN ('ANTIPULGA','CHECKUP','VACINA','VERMIFUGO')),
    CONSTRAINT CK_PROT_STATUS             CHECK (ST_STATUS    IN ('ATRASADO','PENDENTE','REALIZADO')),
    CONSTRAINT FK_PROT_PET                FOREIGN KEY (ID_PET) REFERENCES TB_PET (ID_PET)
);

CREATE TABLE TB_MEDICAMENTO (
    ID_MEDICAMENTO NUMBER        NOT NULL,
    NM_MEDICAMENTO VARCHAR2(200) NOT NULL,
    DS_DOSAGEM     VARCHAR2(100) NOT NULL,
    DS_FREQUENCIA  VARCHAR2(100) NOT NULL,
    DT_INICIO      DATE          NOT NULL,
    DT_FIM         DATE,
    ID_EVENTO      NUMBER        NOT NULL,
    CONSTRAINT TB_MEDICAMENTO_PK PRIMARY KEY (ID_MEDICAMENTO),
    CONSTRAINT FK_MED_EVENTO     FOREIGN KEY (ID_EVENTO) REFERENCES TB_EVENTO_CLINICO (ID_EVENTO)
);

CREATE TABLE TB_ADESAO_MEDICAMENTO (
    ID_ADESAO      NUMBER       NOT NULL,
    DT_DOSE        DATE         NOT NULL,
    ST_TOMOU       CHAR(1)      NOT NULL,
    DS_OBSERVACAO  VARCHAR2(500),
    ID_MEDICAMENTO NUMBER       NOT NULL,
    CONSTRAINT TB_ADESAO_MEDICAMENTO_PK PRIMARY KEY (ID_ADESAO),
    CONSTRAINT CK_ADESAO_TOMOU          CHECK (ST_TOMOU IN ('N','S')),
    CONSTRAINT FK_ADESAO_MED            FOREIGN KEY (ID_MEDICAMENTO) REFERENCES TB_MEDICAMENTO (ID_MEDICAMENTO)
);

CREATE TABLE TB_NOTIFICACAO (
    ID_NOTIFICACAO NUMBER        NOT NULL,
    TP_NOTIFICACAO VARCHAR2(50)  NOT NULL,
    DS_TITULO      VARCHAR2(200) NOT NULL,
    DS_MENSAGEM    VARCHAR2(2000),
    DT_ENVIO       DATE          DEFAULT SYSDATE NOT NULL,
    ST_LIDA        CHAR(1)       NOT NULL,
    ID_TUTOR       NUMBER        NOT NULL,
    ID_PET         NUMBER        NOT NULL,
    CONSTRAINT TB_NOTIFICACAO_PK  PRIMARY KEY (ID_NOTIFICACAO),
    CONSTRAINT CK_NOTIF_TIPO      CHECK (TP_NOTIFICACAO IN ('ALERTA','INFO','LEMBRETE','URGENTE')),
    CONSTRAINT CK_NOTIF_LIDA      CHECK (ST_LIDA        IN ('N','S')),
    CONSTRAINT FK_NOTIF_TUTOR     FOREIGN KEY (ID_TUTOR) REFERENCES TB_TUTOR (ID_TUTOR),
    CONSTRAINT FK_NOTIF_PET       FOREIGN KEY (ID_PET)   REFERENCES TB_PET   (ID_PET)
);

CREATE TABLE TB_SCORE_HISTORICO (
    ID_SCORE      NUMBER      NOT NULL,
    NR_SCORE      NUMBER(5,2) NOT NULL,
    DT_REGISTRO   DATE        DEFAULT SYSDATE NOT NULL,
    DS_OBSERVACAO VARCHAR2(500),
    ID_PET        NUMBER      NOT NULL,
    CONSTRAINT TB_SCORE_HISTORICO_PK PRIMARY KEY (ID_SCORE),
    CONSTRAINT CK_SCORE_VALOR        CHECK (NR_SCORE BETWEEN 0 AND 100),
    CONSTRAINT FK_SCORE_PET          FOREIGN KEY (ID_PET) REFERENCES TB_PET (ID_PET)
);

CREATE TABLE TB_BCS_HISTORICO (
    ID_BCS        NUMBER         NOT NULL,
    NR_BCS        NUMBER(2),
    DS_FOTO_URL   VARCHAR2(500),
    DS_OBSERVACAO VARCHAR2(1000),
    DT_ANALISE    DATE           DEFAULT SYSDATE NOT NULL,
    ID_PET        NUMBER         NOT NULL,
    CONSTRAINT TB_BCS_HISTORICO_PK PRIMARY KEY (ID_BCS),
    CONSTRAINT CK_BCS_VALOR        CHECK (NR_BCS BETWEEN 1 AND 9),
    CONSTRAINT FK_BCS_PET          FOREIGN KEY (ID_PET) REFERENCES TB_PET (ID_PET)
);

CREATE TABLE TB_COLLAR_LEITURA (
    ID_LEITURA     NUMBER      NOT NULL,
    NR_TEMPERATURA NUMBER(5,2) NOT NULL,
    NR_ATIVIDADE   NUMBER(6,2),
    DT_LEITURA     DATE        DEFAULT SYSDATE NOT NULL,
    DS_TOPICO_MQTT VARCHAR2(200),
    ID_PET         NUMBER      NOT NULL,
    CONSTRAINT TB_COLLAR_LEITURA_PK PRIMARY KEY (ID_LEITURA),
    CONSTRAINT CK_COLLAR_TEMP       CHECK (NR_TEMPERATURA BETWEEN 30 AND 45),
    CONSTRAINT FK_COLLAR_PET        FOREIGN KEY (ID_PET) REFERENCES TB_PET (ID_PET)
);

CREATE TABLE TB_ALERTA (
    ID_ALERTA    NUMBER         NOT NULL,
    TP_ALERTA    VARCHAR2(50)   NOT NULL,
    DS_DESCRICAO VARCHAR2(1000),
    NR_VALOR_REF NUMBER(8,2),
    DT_ALERTA    DATE           DEFAULT SYSDATE NOT NULL,
    ST_RESOLVIDO CHAR(1)        NOT NULL,
    ID_PET       NUMBER         NOT NULL,
    CONSTRAINT TB_ALERTA_PK        PRIMARY KEY (ID_ALERTA),
    CONSTRAINT CK_ALERTA_TIPO      CHECK (TP_ALERTA    IN ('ADESAO','BCS_CRITICO','FEBRE','PESO','SEDENTARISMO')),
    CONSTRAINT CK_ALERTA_RESOLVIDO CHECK (ST_RESOLVIDO IN ('N','S')),
    CONSTRAINT FK_ALERTA_PET       FOREIGN KEY (ID_PET) REFERENCES TB_PET (ID_PET)
);

CREATE TABLE TB_AUDITORIA_PETTRACK (
    ID_AUDITORIA          NUMBER          NOT NULL,
    NM_TABELA             VARCHAR2(50)    NOT NULL,
    NM_USUARIO            VARCHAR2(100)   NOT NULL,
    TP_OPERACAO           VARCHAR2(10)    NOT NULL,
    DT_OPERACAO           DATE            DEFAULT SYSDATE NOT NULL,
    DS_VALORES_ANTERIORES VARCHAR2(4000),
    DS_VALORES_NOVOS      VARCHAR2(4000),
    CONSTRAINT TB_AUDITORIA_PK PRIMARY KEY (ID_AUDITORIA),
    CONSTRAINT CK_AUDIT_OPERACAO CHECK (TP_OPERACAO IN ('INSERT', 'UPDATE', 'DELETE'))
);

-- =============================================================================
-- 4. STORED PROCEDURES DE INSERÇÃO COM TRATAMENTO DE EXCEÇÃO
-- =============================================================================

CREATE OR REPLACE PROCEDURE PRC_INSERT_LOG_ERRO(
    P_NM_PROCEDURE IN TB_LOG_ERRO.NM_PROCEDURE%TYPE,
    P_CD_ERRO      IN TB_LOG_ERRO.CD_ERRO%TYPE,
    P_DS_MENSAGEM  IN TB_LOG_ERRO.DS_MENSAGEM%TYPE
)
IS
    PRAGMA AUTONOMOUS_TRANSACTION;
BEGIN
    INSERT INTO TB_LOG_ERRO (ID_LOG, NM_PROCEDURE, NM_USUARIO, DT_OCORRENCIA, CD_ERRO, DS_MENSAGEM) 
        VALUES (SEQ_LOG_ERRO.NEXTVAL, P_NM_PROCEDURE, USER, SYSDATE, P_CD_ERRO, P_DS_MENSAGEM);
    COMMIT;
EXCEPTION
    WHEN DUP_VAL_ON_INDEX THEN
        ROLLBACK;
    WHEN VALUE_ERROR THEN
        ROLLBACK;
    WHEN OTHERS THEN
        ROLLBACK;
END PRC_INSERT_LOG_ERRO;
/

CREATE OR REPLACE PROCEDURE PRC_INSERT_TUTOR(
    P_NM_TUTOR    IN TB_TUTOR.NM_TUTOR%TYPE,
    P_DS_EMAIL    IN TB_TUTOR.DS_EMAIL%TYPE,
    P_NR_TELEFONE IN TB_TUTOR.NR_TELEFONE%TYPE,
    P_DS_ENDERECO IN TB_TUTOR.DS_ENDERECO%TYPE
) IS
BEGIN
    INSERT INTO TB_TUTOR (ID_TUTOR, NM_TUTOR, DS_EMAIL, NR_TELEFONE, DS_ENDERECO) 
        VALUES (SEQ_TUTOR.NEXTVAL, P_NM_TUTOR, P_DS_EMAIL, P_NR_TELEFONE, P_DS_ENDERECO);
    COMMIT;
EXCEPTION
    WHEN DUP_VAL_ON_INDEX THEN
        PRC_INSERT_LOG_ERRO('PRC_INSERT_TUTOR', SQLCODE, SQLERRM);
        COMMIT;
    WHEN VALUE_ERROR THEN
        PRC_INSERT_LOG_ERRO('PRC_INSERT_TUTOR', SQLCODE, SQLERRM);
        COMMIT;
    WHEN OTHERS THEN
        PRC_INSERT_LOG_ERRO('PRC_INSERT_TUTOR', SQLCODE, SQLERRM);
        COMMIT;
END PRC_INSERT_TUTOR;
/

CREATE OR REPLACE PROCEDURE PRC_INSERT_CLINICA (
    P_NM_CLINICA  IN TB_CLINICA.NM_CLINICA%TYPE,
    P_NR_CNPJ     IN TB_CLINICA.NR_CNPJ%TYPE,
    P_DS_EMAIL    IN TB_CLINICA.DS_EMAIL%TYPE,
    P_NR_TELEFONE IN TB_CLINICA.NR_TELEFONE%TYPE,
    P_DS_ENDERECO IN TB_CLINICA.DS_ENDERECO%TYPE
) IS
BEGIN
    INSERT INTO TB_CLINICA (ID_CLINICA, NM_CLINICA, NR_CNPJ, DS_EMAIL, NR_TELEFONE, DS_ENDERECO) 
        VALUES (SEQ_CLINICA.NEXTVAL, P_NM_CLINICA, P_NR_CNPJ, P_DS_EMAIL, P_NR_TELEFONE, P_DS_ENDERECO);
    COMMIT;
EXCEPTION
    WHEN DUP_VAL_ON_INDEX THEN
        PRC_INSERT_LOG_ERRO('PRC_INSERT_CLINICA', SQLCODE, SQLERRM);
        COMMIT;
    WHEN VALUE_ERROR THEN
        PRC_INSERT_LOG_ERRO('PRC_INSERT_CLINICA', SQLCODE, SQLERRM);
        COMMIT;
    WHEN OTHERS THEN
        PRC_INSERT_LOG_ERRO('PRC_INSERT_CLINICA', SQLCODE, SQLERRM);
        COMMIT;
END PRC_INSERT_CLINICA;
/

CREATE OR REPLACE PROCEDURE PRC_INSERT_PET (
    P_NM_PET        IN TB_PET.NM_PET%TYPE,
    P_DS_ESPECIE    IN TB_PET.DS_ESPECIE%TYPE,
    P_DS_RACA       IN TB_PET.DS_RACA%TYPE,
    P_DS_SEXO       IN TB_PET.DS_SEXO%TYPE,
    P_NR_IDADE_ANOS IN TB_PET.NR_IDADE_ANOS%TYPE,
    P_NR_PESO_KG    IN TB_PET.NR_PESO_KG%TYPE,
    P_ID_TUTOR      IN TB_PET.ID_TUTOR%TYPE,
    P_ID_CLINICA    IN TB_PET.ID_CLINICA%TYPE
) IS
BEGIN
    INSERT INTO TB_PET (ID_PET, NM_PET, DS_ESPECIE, DS_RACA, DS_SEXO, NR_IDADE_ANOS, NR_PESO_KG, ID_TUTOR, ID_CLINICA) 
        VALUES (SEQ_PET.NEXTVAL, P_NM_PET, P_DS_ESPECIE, P_DS_RACA, P_DS_SEXO, P_NR_IDADE_ANOS, P_NR_PESO_KG, P_ID_TUTOR, P_ID_CLINICA);
    COMMIT;
EXCEPTION
    WHEN DUP_VAL_ON_INDEX THEN
        PRC_INSERT_LOG_ERRO('PRC_INSERT_PET', SQLCODE, SQLERRM);
        COMMIT;
    WHEN VALUE_ERROR THEN
        PRC_INSERT_LOG_ERRO('PRC_INSERT_PET', SQLCODE, SQLERRM);
        COMMIT;
    WHEN OTHERS THEN
        PRC_INSERT_LOG_ERRO('PRC_INSERT_PET', SQLCODE, SQLERRM);
        COMMIT;
END PRC_INSERT_PET;
/

CREATE OR REPLACE PROCEDURE PRC_INSERT_EVENTO_CLINICO (
    P_TP_EVENTO      IN TB_EVENTO_CLINICO.TP_EVENTO%TYPE,
    P_DT_EVENTO      IN TB_EVENTO_CLINICO.DT_EVENTO%TYPE,
    P_DS_DIAGNOSTICO IN TB_EVENTO_CLINICO.DS_DIAGNOSTICO%TYPE,
    P_DS_OBSERVACAO  IN TB_EVENTO_CLINICO.DS_OBSERVACAO%TYPE,
    P_ID_PET         IN TB_EVENTO_CLINICO.ID_PET%TYPE,
    P_ID_CLINICA     IN TB_EVENTO_CLINICO.ID_CLINICA%TYPE
) IS
BEGIN
    INSERT INTO TB_EVENTO_CLINICO (ID_EVENTO, TP_EVENTO, DT_EVENTO, DS_DIAGNOSTICO, DS_OBSERVACAO, ID_PET, ID_CLINICA) 
        VALUES (SEQ_EVENTO_CLINICO.NEXTVAL, P_TP_EVENTO, P_DT_EVENTO, P_DS_DIAGNOSTICO, P_DS_OBSERVACAO, P_ID_PET, P_ID_CLINICA);
    COMMIT;
EXCEPTION
    WHEN DUP_VAL_ON_INDEX THEN
        PRC_INSERT_LOG_ERRO('PRC_INSERT_EVENTO_CLINICO', SQLCODE, SQLERRM);
        COMMIT;
    WHEN NO_DATA_FOUND THEN
        PRC_INSERT_LOG_ERRO('PRC_INSERT_EVENTO_CLINICO', SQLCODE, SQLERRM);
        COMMIT;
    WHEN OTHERS THEN
        PRC_INSERT_LOG_ERRO('PRC_INSERT_EVENTO_CLINICO', SQLCODE, SQLERRM);
        COMMIT;
END PRC_INSERT_EVENTO_CLINICO;
/

CREATE OR REPLACE PROCEDURE PRC_INSERT_PROTOCOLO_PREVENTIVO(
    P_TP_PROTOCOLO IN TB_PROTOCOLO_PREVENTIVO.TP_PROTOCOLO%TYPE,
    P_NM_PROTOCOLO IN TB_PROTOCOLO_PREVENTIVO.NM_PROTOCOLO%TYPE,
    P_DT_APLICACAO IN TB_PROTOCOLO_PREVENTIVO.DT_APLICACAO%TYPE,
    P_DT_PROXIMA   IN TB_PROTOCOLO_PREVENTIVO.DT_PROXIMA%TYPE,
    P_ST_STATUS    IN TB_PROTOCOLO_PREVENTIVO.ST_STATUS%TYPE,
    P_ID_PET       IN TB_PROTOCOLO_PREVENTIVO.ID_PET%TYPE
) IS
BEGIN
    INSERT INTO TB_PROTOCOLO_PREVENTIVO (ID_PROTOCOLO, TP_PROTOCOLO, NM_PROTOCOLO, DT_APLICACAO, DT_PROXIMA, ST_STATUS, ID_PET)
        VALUES (SEQ_PROTOCOLO.NEXTVAL, P_TP_PROTOCOLO, P_NM_PROTOCOLO, P_DT_APLICACAO, P_DT_PROXIMA, P_ST_STATUS, P_ID_PET);
    COMMIT;
EXCEPTION
    WHEN DUP_VAL_ON_INDEX THEN
        PRC_INSERT_LOG_ERRO('PRC_INSERT_PROTOCOLO_PREVENTIVO', SQLCODE, SQLERRM);
        COMMIT;
    WHEN NO_DATA_FOUND THEN
        PRC_INSERT_LOG_ERRO('PRC_INSERT_PROTOCOLO_PREVENTIVO', SQLCODE, SQLERRM);
        COMMIT;
    WHEN OTHERS THEN
        PRC_INSERT_LOG_ERRO('PRC_INSERT_PROTOCOLO_PREVENTIVO', SQLCODE, SQLERRM);
        COMMIT;
END PRC_INSERT_PROTOCOLO_PREVENTIVO;
/

CREATE OR REPLACE PROCEDURE PRC_INSERT_MEDICAMENTO (
    P_NM_MEDICAMENTO IN TB_MEDICAMENTO.NM_MEDICAMENTO%TYPE,
    P_DS_DOSAGEM     IN TB_MEDICAMENTO.DS_DOSAGEM%TYPE,
    P_DS_FREQUENCIA  IN TB_MEDICAMENTO.DS_FREQUENCIA%TYPE,
    P_DT_INICIO      IN TB_MEDICAMENTO.DT_INICIO%TYPE,
    P_DT_FIM         IN TB_MEDICAMENTO.DT_FIM%TYPE,
    P_ID_EVENTO      IN TB_MEDICAMENTO.ID_EVENTO%TYPE
) IS
BEGIN
    INSERT INTO TB_MEDICAMENTO (ID_MEDICAMENTO, NM_MEDICAMENTO, DS_DOSAGEM, DS_FREQUENCIA, DT_INICIO, DT_FIM, ID_EVENTO) 
        VALUES (SEQ_MEDICAMENTO.NEXTVAL, P_NM_MEDICAMENTO, P_DS_DOSAGEM, P_DS_FREQUENCIA, P_DT_INICIO, P_DT_FIM, P_ID_EVENTO);
    COMMIT;
EXCEPTION
    WHEN VALUE_ERROR THEN
        PRC_INSERT_LOG_ERRO('PRC_INSERT_MEDICAMENTO', SQLCODE, SQLERRM);
        COMMIT;
    WHEN NO_DATA_FOUND THEN
        PRC_INSERT_LOG_ERRO('PRC_INSERT_MEDICAMENTO', SQLCODE, SQLERRM);
        COMMIT;
    WHEN OTHERS THEN
        PRC_INSERT_LOG_ERRO('PRC_INSERT_MEDICAMENTO', SQLCODE, SQLERRM);
        COMMIT;
END PRC_INSERT_MEDICAMENTO;
/

CREATE OR REPLACE PROCEDURE PRC_INSERT_ADESAO_MEDICAMENTO (
    P_DT_DOSE        IN TB_ADESAO_MEDICAMENTO.DT_DOSE%TYPE,
    P_ST_TOMOU       IN TB_ADESAO_MEDICAMENTO.ST_TOMOU%TYPE,
    P_DS_OBSERVACAO  IN TB_ADESAO_MEDICAMENTO.DS_OBSERVACAO%TYPE,
    P_ID_MEDICAMENTO IN TB_ADESAO_MEDICAMENTO.ID_MEDICAMENTO%TYPE
) IS
BEGIN
    INSERT INTO TB_ADESAO_MEDICAMENTO (ID_ADESAO, DT_DOSE, ST_TOMOU, DS_OBSERVACAO, ID_MEDICAMENTO) 
        VALUES (SEQ_ADESAO.NEXTVAL, P_DT_DOSE, P_ST_TOMOU, P_DS_OBSERVACAO, P_ID_MEDICAMENTO);
    COMMIT;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        PRC_INSERT_LOG_ERRO('PRC_INSERT_ADESAO_MEDICAMENTO', SQLCODE, SQLERRM);
        COMMIT;
    WHEN VALUE_ERROR THEN
        PRC_INSERT_LOG_ERRO('PRC_INSERT_ADESAO_MEDICAMENTO', SQLCODE, SQLERRM);
        COMMIT;
    WHEN OTHERS THEN
        PRC_INSERT_LOG_ERRO('PRC_INSERT_ADESAO_MEDICAMENTO', SQLCODE, SQLERRM);
        COMMIT;
END PRC_INSERT_ADESAO_MEDICAMENTO;
/

CREATE OR REPLACE PROCEDURE PRC_INSERT_NOTIFICACAO (
    P_TP_NOTIFICACAO IN TB_NOTIFICACAO.TP_NOTIFICACAO%TYPE,
    P_DS_TITULO      IN TB_NOTIFICACAO.DS_TITULO%TYPE,
    P_DS_MENSAGEM    IN TB_NOTIFICACAO.DS_MENSAGEM%TYPE,
    P_ST_LIDA        IN TB_NOTIFICACAO.ST_LIDA%TYPE,
    P_ID_TUTOR       IN TB_NOTIFICACAO.ID_TUTOR%TYPE,
    P_ID_PET         IN TB_NOTIFICACAO.ID_PET%TYPE
) IS
BEGIN
    INSERT INTO TB_NOTIFICACAO (ID_NOTIFICACAO, TP_NOTIFICACAO, DS_TITULO, DS_MENSAGEM, DT_ENVIO, ST_LIDA, ID_TUTOR, ID_PET) 
        VALUES (SEQ_NOTIFICACAO.NEXTVAL, P_TP_NOTIFICACAO, P_DS_TITULO, P_DS_MENSAGEM, SYSDATE, P_ST_LIDA, P_ID_TUTOR, P_ID_PET);
    COMMIT;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        PRC_INSERT_LOG_ERRO('PRC_INSERT_NOTIFICACAO', SQLCODE, SQLERRM);
        COMMIT;
    WHEN VALUE_ERROR THEN
        PRC_INSERT_LOG_ERRO('PRC_INSERT_NOTIFICACAO', SQLCODE, SQLERRM);
        COMMIT;
    WHEN OTHERS THEN
        PRC_INSERT_LOG_ERRO('PRC_INSERT_NOTIFICACAO', SQLCODE, SQLERRM);
        COMMIT;
END PRC_INSERT_NOTIFICACAO;
/

CREATE OR REPLACE PROCEDURE PRC_INSERT_SCORE_HISTORICO (
    P_NR_SCORE      IN TB_SCORE_HISTORICO.NR_SCORE%TYPE,
    P_DS_OBSERVACAO IN TB_SCORE_HISTORICO.DS_OBSERVACAO%TYPE,
    P_ID_PET        IN TB_SCORE_HISTORICO.ID_PET%TYPE
) IS
BEGIN
    INSERT INTO TB_SCORE_HISTORICO (ID_SCORE, NR_SCORE, DT_REGISTRO, DS_OBSERVACAO, ID_PET)
        VALUES (SEQ_SCORE_HIST.NEXTVAL, P_NR_SCORE, SYSDATE, P_DS_OBSERVACAO, P_ID_PET);
    COMMIT;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        PRC_INSERT_LOG_ERRO('PRC_INSERT_SCORE_HISTORICO', SQLCODE, SQLERRM);
        COMMIT;
    WHEN VALUE_ERROR THEN
        PRC_INSERT_LOG_ERRO('PRC_INSERT_SCORE_HISTORICO', SQLCODE, SQLERRM);
        COMMIT;
    WHEN OTHERS THEN
        PRC_INSERT_LOG_ERRO('PRC_INSERT_SCORE_HISTORICO', SQLCODE, SQLERRM);
        COMMIT;
END PRC_INSERT_SCORE_HISTORICO;
/

CREATE OR REPLACE PROCEDURE PRC_INSERT_BCS_HISTORICO (
    P_NR_BCS        IN TB_BCS_HISTORICO.NR_BCS%TYPE,
    P_DS_FOTO_URL   IN TB_BCS_HISTORICO.DS_FOTO_URL%TYPE,
    P_DS_OBSERVACAO IN TB_BCS_HISTORICO.DS_OBSERVACAO%TYPE,
    P_ID_PET        IN TB_BCS_HISTORICO.ID_PET%TYPE
) IS
BEGIN
    INSERT INTO TB_BCS_HISTORICO (ID_BCS, NR_BCS, DS_FOTO_URL, DS_OBSERVACAO, DT_ANALISE, ID_PET) 
        VALUES (SEQ_BCS_HIST.NEXTVAL, P_NR_BCS, P_DS_FOTO_URL, P_DS_OBSERVACAO, SYSDATE, P_ID_PET);
    COMMIT;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        PRC_INSERT_LOG_ERRO('PRC_INSERT_BCS_HISTORICO', SQLCODE, SQLERRM);
        COMMIT;
    WHEN VALUE_ERROR THEN
        PRC_INSERT_LOG_ERRO('PRC_INSERT_BCS_HISTORICO', SQLCODE, SQLERRM);
        COMMIT;
    WHEN OTHERS THEN
        PRC_INSERT_LOG_ERRO('PRC_INSERT_BCS_HISTORICO', SQLCODE, SQLERRM);
        COMMIT;
END PRC_INSERT_BCS_HISTORICO;
/

CREATE OR REPLACE PROCEDURE PRC_INSERT_COLLAR_LEITURA (
    P_NR_TEMPERATURA IN TB_COLLAR_LEITURA.NR_TEMPERATURA%TYPE,
    P_NR_ATIVIDADE   IN TB_COLLAR_LEITURA.NR_ATIVIDADE%TYPE,
    P_DS_TOPICO_MQTT IN TB_COLLAR_LEITURA.DS_TOPICO_MQTT%TYPE,
    P_ID_PET         IN TB_COLLAR_LEITURA.ID_PET%TYPE
) IS
BEGIN
    INSERT INTO TB_COLLAR_LEITURA (ID_LEITURA, NR_TEMPERATURA, NR_ATIVIDADE, DT_LEITURA, DS_TOPICO_MQTT, ID_PET) 
        VALUES (SEQ_COLLAR.NEXTVAL, P_NR_TEMPERATURA, P_NR_ATIVIDADE, SYSDATE, P_DS_TOPICO_MQTT, P_ID_PET);
    COMMIT;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        PRC_INSERT_LOG_ERRO('PRC_INSERT_COLLAR_LEITURA', SQLCODE, SQLERRM);
        COMMIT;
    WHEN VALUE_ERROR THEN
        PRC_INSERT_LOG_ERRO('PRC_INSERT_COLLAR_LEITURA', SQLCODE, SQLERRM);
        COMMIT;
    WHEN OTHERS THEN
        PRC_INSERT_LOG_ERRO('PRC_INSERT_COLLAR_LEITURA', SQLCODE, SQLERRM);
        COMMIT;
END PRC_INSERT_COLLAR_LEITURA;
/

CREATE OR REPLACE PROCEDURE PRC_INSERT_ALERTA (
    P_TP_ALERTA    IN TB_ALERTA.TP_ALERTA%TYPE,
    P_DS_DESCRICAO IN TB_ALERTA.DS_DESCRICAO%TYPE,
    P_NR_VALOR_REF IN TB_ALERTA.NR_VALOR_REF%TYPE,
    P_ST_RESOLVIDO IN TB_ALERTA.ST_RESOLVIDO%TYPE,
    P_ID_PET       IN TB_ALERTA.ID_PET%TYPE
) IS
BEGIN
    INSERT INTO TB_ALERTA (ID_ALERTA, TP_ALERTA, DS_DESCRICAO, NR_VALOR_REF, DT_ALERTA, ST_RESOLVIDO, ID_PET) 
        VALUES (SEQ_ALERTA.NEXTVAL, P_TP_ALERTA, P_DS_DESCRICAO, P_NR_VALOR_REF, SYSDATE, P_ST_RESOLVIDO, P_ID_PET);
    COMMIT;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        PRC_INSERT_LOG_ERRO('PRC_INSERT_ALERTA', SQLCODE, SQLERRM);
        COMMIT;
    WHEN VALUE_ERROR THEN
        PRC_INSERT_LOG_ERRO('PRC_INSERT_ALERTA', SQLCODE, SQLERRM);
        COMMIT;
    WHEN OTHERS THEN
        PRC_INSERT_LOG_ERRO('PRC_INSERT_ALERTA', SQLCODE, SQLERRM);
        COMMIT;
END PRC_INSERT_ALERTA;
/

-- =============================================================================
-- 5. CARGA DE DADOS INICIAIS (POVOAMENTO VIA PROCEDURES)
-- =============================================================================

-- Clínicas
DECLARE
    V_NM_CLINICA  VARCHAR2(200) := 'VetLife Clínica Veterinária';
    V_NR_CNPJ     VARCHAR2(18)  := '758748948123958473';
    V_DS_EMAIL    VARCHAR2(200) := 'vetlife@gmail.com';
    V_NR_TELEFONE VARCHAR2(20)  := '1198675876466';
    V_DS_ENDERECO VARCHAR2(300) := 'Rua Gamelinha, 99';
BEGIN
    PRC_INSERT_CLINICA(V_NM_CLINICA, V_NR_CNPJ, V_DS_EMAIL, V_NR_TELEFONE, V_DS_ENDERECO);
END;
/

DECLARE
    V_NM_CLINICA  VARCHAR2(200) := 'PetCare Hospital Animal';
    V_NR_CNPJ     VARCHAR2(18)  := '455874764815675783';
    V_DS_EMAIL    VARCHAR2(200) := 'PetCare@gmail.com';
    V_NR_TELEFONE VARCHAR2(20)  := '11945758765566';
    V_DS_ENDERECO VARCHAR2(300) := 'Rua alvredo, 143';
BEGIN
    PRC_INSERT_CLINICA(V_NM_CLINICA, V_NR_CNPJ, V_DS_EMAIL, V_NR_TELEFONE, V_DS_ENDERECO);
END;
/

DECLARE
    V_NM_CLINICA  VARCHAR2(200) := 'Animal Center Clínica Veterinária';
    V_NR_CNPJ     VARCHAR2(18)  := '12345678000101';
    V_DS_EMAIL    VARCHAR2(200) := 'animalcenter@gmail.com';
    V_NR_TELEFONE VARCHAR2(20)  := '11988887777';
    V_DS_ENDERECO VARCHAR2(300) := 'Rua Augusta, 250';
BEGIN
    PRC_INSERT_CLINICA(V_NM_CLINICA, V_NR_CNPJ, V_DS_EMAIL, V_NR_TELEFONE, V_DS_ENDERECO);
END;
/

DECLARE
    V_NM_CLINICA  VARCHAR2(200) := 'Pet Saúde Clínica Veterinária';
    V_NR_CNPJ     VARCHAR2(18)  := '23456789000102';
    V_DS_EMAIL    VARCHAR2(200) := 'petsaude@gmail.com';
    V_NR_TELEFONE VARCHAR2(20)  := '11977776666';
    V_DS_ENDERECO VARCHAR2(300) := 'Avenida Paulista, 1000';
BEGIN
    PRC_INSERT_CLINICA(V_NM_CLINICA, V_NR_CNPJ, V_DS_EMAIL, V_NR_TELEFONE, V_DS_ENDERECO);
END;
/

DECLARE
    V_NM_CLINICA  VARCHAR2(200) := 'Hospital Vet Mais';
    V_NR_CNPJ     VARCHAR2(18)  := '34567890000103';
    V_DS_EMAIL    VARCHAR2(200) := 'vetmais@gmail.com';
    V_NR_TELEFONE VARCHAR2(20)  := '11966665555';
    V_DS_ENDERECO VARCHAR2(300) := 'Rua Vergueiro, 500';
BEGIN
    PRC_INSERT_CLINICA(V_NM_CLINICA, V_NR_CNPJ, V_DS_EMAIL, V_NR_TELEFONE, V_DS_ENDERECO);
END;
/

-- Tutores
DECLARE
    V_NM_TUTOR    VARCHAR2(150) := 'Ana Paula Silva';
    V_DS_EMAIL    VARCHAR2(200) := 'ana@icloud.com';
    V_NR_TELEFONE VARCHAR2(20)  := '11975647387';
    V_DS_ENDERECO VARCHAR2(300) := 'rua jose, 89';
BEGIN
    PRC_INSERT_TUTOR(V_NM_TUTOR, V_DS_EMAIL, V_NR_TELEFONE, V_DS_ENDERECO);
END;
/

DECLARE
    V_NM_TUTOR    VARCHAR2(150) := 'Carlos Eduardo Santos';
    V_DS_EMAIL    VARCHAR2(200) := 'CARLAO@icloud.com';
    V_NR_TELEFONE VARCHAR2(20)  := '119387685764';
    V_DS_ENDERECO VARCHAR2(300) := 'rua pedro de souza, 56';
BEGIN
    PRC_INSERT_TUTOR(V_NM_TUTOR, V_DS_EMAIL, V_NR_TELEFONE, V_DS_ENDERECO);
END;
/

DECLARE
    V_NM_TUTOR    VARCHAR2(150) := 'Mariana Oliveira';
    V_DS_EMAIL    VARCHAR2(200) := 'Mariana@icloud.com';
    V_NR_TELEFONE VARCHAR2(20)  := '11986758744';
    V_DS_ENDERECO VARCHAR2(300) := 'rua jose mourinho, 59';
BEGIN
    PRC_INSERT_TUTOR(V_NM_TUTOR, V_DS_EMAIL, V_NR_TELEFONE, V_DS_ENDERECO);
END;
/

DECLARE
    V_NM_TUTOR    VARCHAR2(150) := 'João Pedro Almeida';
    V_DS_EMAIL    VARCHAR2(200) := 'joao@gmail.com';
    V_NR_TELEFONE VARCHAR2(20)  := '11955554444';
    V_DS_ENDERECO VARCHAR2(300) := 'Rua Consolação, 120';
BEGIN
    PRC_INSERT_TUTOR(V_NM_TUTOR, V_DS_EMAIL, V_NR_TELEFONE, V_DS_ENDERECO);
END;
/

DECLARE
    V_NM_TUTOR    VARCHAR2(150) := 'Beatriz Martins';
    V_DS_EMAIL    VARCHAR2(200) := 'beatriz@gmail.com';
    V_NR_TELEFONE VARCHAR2(20)  := '11944443333';
    V_DS_ENDERECO VARCHAR2(300) := 'Rua Haddock Lobo, 300';
BEGIN
    PRC_INSERT_TUTOR(V_NM_TUTOR, V_DS_EMAIL, V_NR_TELEFONE, V_DS_ENDERECO);
END;
/

-- Pets
DECLARE
    V_NM_PET        VARCHAR2(100) := 'Thor';
    V_DS_ESPECIE    VARCHAR2(50)  := 'Cão';
    V_DS_RACA       VARCHAR2(100) := 'Golden Retriever';
    V_DS_SEXO       CHAR(1)       := 'M';
    V_NR_IDADE_ANOS NUMBER(3,1)   := 8;
    V_NR_PESO_KG    NUMBER(6,3)   := 12;
    V_ID_TUTOR      NUMBER        := 3;
    V_ID_CLINICA    NUMBER        := 1;
BEGIN
    PRC_INSERT_PET(V_NM_PET, V_DS_ESPECIE, V_DS_RACA, V_DS_SEXO, V_NR_IDADE_ANOS, V_NR_PESO_KG, V_ID_TUTOR, V_ID_CLINICA);
END;
/

DECLARE
    V_NM_PET        VARCHAR2(100) := 'Luna';
    V_DS_ESPECIE    VARCHAR2(50)  := 'Cão';
    V_DS_RACA       VARCHAR2(100) := 'Poodle';
    V_DS_SEXO       CHAR(1)       := 'F';
    V_NR_IDADE_ANOS NUMBER(3,1)   := 9;
    V_NR_PESO_KG    NUMBER(6,3)   := 10;
    V_ID_TUTOR      NUMBER        := 2;
    V_ID_CLINICA    NUMBER        := 1;
BEGIN
    PRC_INSERT_PET(V_NM_PET, V_DS_ESPECIE, V_DS_RACA, V_DS_SEXO, V_NR_IDADE_ANOS, V_NR_PESO_KG, V_ID_TUTOR, V_ID_CLINICA);
END;
/

DECLARE
    V_NM_PET        VARCHAR2(100) := 'Bob';
    V_DS_ESPECIE    VARCHAR2(50)  := 'Cão';
    V_DS_RACA       VARCHAR2(100) := 'Bulldog';
    V_DS_SEXO       CHAR(1)       := 'M';
    V_NR_IDADE_ANOS NUMBER(3,1)   := 12;
    V_NR_PESO_KG    NUMBER(6,3)   := 16;
    V_ID_TUTOR      NUMBER        := 1;
    V_ID_CLINICA    NUMBER        := 1;
BEGIN
    PRC_INSERT_PET(V_NM_PET, V_DS_ESPECIE, V_DS_RACA, V_DS_SEXO, V_NR_IDADE_ANOS, V_NR_PESO_KG, V_ID_TUTOR, V_ID_CLINICA);
END;
/

DECLARE
    V_NM_PET        VARCHAR2(100) := 'Nina';
    V_DS_ESPECIE    VARCHAR2(50)  := 'Cão';
    V_DS_RACA       VARCHAR2(100) := 'SRD';
    V_DS_SEXO       CHAR(1)       := 'F';
    V_NR_IDADE_ANOS NUMBER(3,1)   := 6;
    V_NR_PESO_KG    NUMBER(6,3)   := 10;
    V_ID_TUTOR      NUMBER        := 2;
    V_ID_CLINICA    NUMBER        := 2;
BEGIN
   PRC_INSERT_PET(V_NM_PET, V_DS_ESPECIE, V_DS_RACA, V_DS_SEXO, V_NR_IDADE_ANOS, V_NR_PESO_KG, V_ID_TUTOR, V_ID_CLINICA);
END;
/

DECLARE
    V_NM_PET        VARCHAR2(100) := 'MAX';
    V_DS_ESPECIE    VARCHAR2(50)  := 'Cão';
    V_DS_RACA       VARCHAR2(100) := 'SRD';
    V_DS_SEXO       CHAR(1)       := 'M';
    V_NR_IDADE_ANOS NUMBER(3,1)   := 12;
    V_NR_PESO_KG    NUMBER(6,3)   := 10.3;
    V_ID_TUTOR      NUMBER        := 2;
    V_ID_CLINICA    NUMBER        := 1;
BEGIN
    PRC_INSERT_PET(V_NM_PET, V_DS_ESPECIE, V_DS_RACA, V_DS_SEXO, V_NR_IDADE_ANOS, V_NR_PESO_KG, V_ID_TUTOR, V_ID_CLINICA);
END;
/

-- Eventos Clínicos
DECLARE
    V_TP_EVENTO      VARCHAR2(50)   := 'CONSULTA';
    V_DT_EVENTO      DATE           := TO_DATE('10/01/2025', 'DD/MM/YYYY');
    V_DS_DIAGNOSTICO VARCHAR2(1000) := 'Melhora parcial';
    V_DS_OBSERVACAO  VARCHAR2(2000) := 'COCEIRA';
    V_ID_PET         NUMBER         := 3;
    V_ID_CLINICA     NUMBER         := 2;
BEGIN
     PRC_INSERT_EVENTO_CLINICO(V_TP_EVENTO, V_DT_EVENTO, V_DS_DIAGNOSTICO, V_DS_OBSERVACAO, V_ID_PET, V_ID_CLINICA);
END;
/

DECLARE
    V_TP_EVENTO      VARCHAR2(50)   := 'CONSULTA';
    V_DT_EVENTO      DATE           := TO_DATE ('10/01/2025', 'DD/MM/YYYY');
    V_DS_DIAGNOSTICO VARCHAR2(1000) := 'Dermatite alérgica';
    V_DS_OBSERVACAO  VARCHAR2(2000) := 'Coceira intensa';
    V_ID_PET         NUMBER         := 3;
    V_ID_CLINICA     NUMBER         := 2;
BEGIN
     PRC_INSERT_EVENTO_CLINICO(V_TP_EVENTO, V_DT_EVENTO, V_DS_DIAGNOSTICO, V_DS_OBSERVACAO, V_ID_PET, V_ID_CLINICA);
END;
/

DECLARE
    V_TP_EVENTO      VARCHAR2(50)   := 'RETORNO';
    V_DT_EVENTO      DATE           := TO_DATE ('15/02/2025', 'DD/MM/YYYY');
    V_DS_DIAGNOSTICO VARCHAR2(1000) := 'Melhora parcial';
    V_DS_OBSERVACAO  VARCHAR2(2000) := 'Continuar medicamento';
    V_ID_PET         NUMBER         := 4;
    V_ID_CLINICA     NUMBER         := 2;
BEGIN
     PRC_INSERT_EVENTO_CLINICO(V_TP_EVENTO, V_DT_EVENTO, V_DS_DIAGNOSTICO, V_DS_OBSERVACAO, V_ID_PET, V_ID_CLINICA);
END;
/

DECLARE
    V_TP_EVENTO      VARCHAR2(50)   := 'CONSULTA';
    V_DT_EVENTO      DATE           := TO_DATE ('20/01/2025', 'DD/MM/YYYY');
    V_DS_DIAGNOSTICO VARCHAR2(1000) := 'Obesidade';
    V_DS_OBSERVACAO  VARCHAR2(2000) := 'Dieta recomendada';
    V_ID_PET         NUMBER         := 5;
    V_ID_CLINICA     NUMBER         := 1;
BEGIN
     PRC_INSERT_EVENTO_CLINICO(V_TP_EVENTO, V_DT_EVENTO, V_DS_DIAGNOSTICO, V_DS_OBSERVACAO, V_ID_PET, V_ID_CLINICA);
END;
/

DECLARE
    V_TP_EVENTO      VARCHAR2(50)   := 'EXAME';
    V_DT_EVENTO      DATE           := TO_DATE ('05/03/2025', 'DD/MM/YYYY');
    V_DS_DIAGNOSTICO VARCHAR2(1000) := 'Hemograma';
    V_DS_OBSERVACAO  VARCHAR2(2000) := NULL;
    V_ID_PET         NUMBER         := 5;
    V_ID_CLINICA     NUMBER         := 2;
BEGIN
     PRC_INSERT_EVENTO_CLINICO(V_TP_EVENTO, V_DT_EVENTO, V_DS_DIAGNOSTICO, V_DS_OBSERVACAO, V_ID_PET, V_ID_CLINICA);
END;
/

DECLARE
    V_TP_EVENTO      VARCHAR2(50)   := 'CONSULTA';
    V_DT_EVENTO      DATE           := TO_DATE ('28/02/2025', 'DD/MM/YYYY');
    V_DS_DIAGNOSTICO VARCHAR2(1000) := 'Boa recuperação';
    V_DS_OBSERVACAO  VARCHAR2(2000) := NULL;
    V_ID_PET         NUMBER         := 3;
    V_ID_CLINICA     NUMBER         := 1;
BEGIN
     PRC_INSERT_EVENTO_CLINICO(V_TP_EVENTO, V_DT_EVENTO, V_DS_DIAGNOSTICO, V_DS_OBSERVACAO, V_ID_PET, V_ID_CLINICA);
END;
/

-- Protocolos Preventivos
DECLARE
    V_TP_PROTOCOLO VARCHAR2(50)  := 'VACINA';
    V_NM_PROTOCOLO VARCHAR2(200) := 'V10';
    V_DT_APLICACAO DATE          := TO_DATE('05/01/2025', 'DD/MM/YYYY');
    V_DT_PROXIMA   DATE          := TO_DATE('05/01/2026', 'DD/MM/YYYY');
    V_ST_STATUS    VARCHAR2(20)  := 'REALIZADO';
    V_ID_PET       NUMBER        := 3;
BEGIN 
    PRC_INSERT_PROTOCOLO_PREVENTIVO(V_TP_PROTOCOLO, V_NM_PROTOCOLO, V_DT_APLICACAO, V_DT_PROXIMA, V_ST_STATUS, V_ID_PET);
END;
/

DECLARE
    V_TP_PROTOCOLO VARCHAR2(50)  := 'VERMIFUGO';
    V_NM_PROTOCOLO VARCHAR2(200) := 'Drontal';
    V_DT_APLICACAO DATE          := TO_DATE('05/02/2025', 'DD/MM/YYYY');
    V_DT_PROXIMA   DATE          := TO_DATE('05/05/2026', 'DD/MM/YYYY');
    V_ST_STATUS    VARCHAR2(20)  := 'REALIZADO';
    V_ID_PET       NUMBER        := 5;
BEGIN 
    PRC_INSERT_PROTOCOLO_PREVENTIVO(V_TP_PROTOCOLO, V_NM_PROTOCOLO, V_DT_APLICACAO, V_DT_PROXIMA, V_ST_STATUS, V_ID_PET);
END;
/

DECLARE
    V_TP_PROTOCOLO VARCHAR2(50)  := 'VACINA';
    V_NM_PROTOCOLO VARCHAR2(200) := 'Antirrábica';
    V_DT_APLICACAO DATE          := TO_DATE('10/01/2025', 'DD/MM/YYYY');
    V_DT_PROXIMA   DATE          := TO_DATE('01/03/2025', 'DD/MM/YYYY');
    V_ST_STATUS    VARCHAR2(20)  := 'REALIZADO';
    V_ID_PET       NUMBER        := 1;
BEGIN 
    PRC_INSERT_PROTOCOLO_PREVENTIVO(V_TP_PROTOCOLO, V_NM_PROTOCOLO, V_DT_APLICACAO, V_DT_PROXIMA, V_ST_STATUS, V_ID_PET);
END;
/

DECLARE
    V_TP_PROTOCOLO VARCHAR2(50)  := 'CHECKUP';
    V_NM_PROTOCOLO VARCHAR2(200) := 'Checku Plus';
    V_DT_APLICACAO DATE          := TO_DATE('01/04/2025', 'DD/MM/YYYY');
    V_DT_PROXIMA   DATE          := TO_DATE('01/09/2025', 'DD/MM/YYYY');
    V_ST_STATUS    VARCHAR2(20)  := 'REALIZADO';
    V_ID_PET       NUMBER        := 1;
BEGIN 
    PRC_INSERT_PROTOCOLO_PREVENTIVO(V_TP_PROTOCOLO, V_NM_PROTOCOLO, V_DT_APLICACAO, V_DT_PROXIMA, V_ST_STATUS, V_ID_PET);
END;
/

DECLARE
    V_TP_PROTOCOLO VARCHAR2(50)  := 'ANTIPULGA';
    V_NM_PROTOCOLO VARCHAR2(200) := 'Frontiline';
    V_DT_APLICACAO DATE          := TO_DATE('10/02/2025', 'DD/MM/YYYY');
    V_DT_PROXIMA   DATE          := TO_DATE('10/05/2025', 'DD/MM/YYYY');
    V_ST_STATUS    VARCHAR2(20)  := 'ATRASADO';
    V_ID_PET       NUMBER        := 4;
BEGIN 
    PRC_INSERT_PROTOCOLO_PREVENTIVO(V_TP_PROTOCOLO, V_NM_PROTOCOLO, V_DT_APLICACAO, V_DT_PROXIMA, V_ST_STATUS, V_ID_PET);
END;
/

DECLARE
    V_TP_PROTOCOLO VARCHAR2(50)  := 'VACINA';
    V_NM_PROTOCOLO VARCHAR2(200) := 'V10';
    V_DT_APLICACAO DATE          := NULL;
    V_DT_PROXIMA   DATE          := TO_DATE('15/04/2025', 'DD/MM/YYYY');
    V_ST_STATUS    VARCHAR2(20)  := 'PENDENTE';
    V_ID_PET       NUMBER        := 2;
BEGIN 
    PRC_INSERT_PROTOCOLO_PREVENTIVO(V_TP_PROTOCOLO, V_NM_PROTOCOLO, V_DT_APLICACAO, V_DT_PROXIMA, V_ST_STATUS, V_ID_PET);
END;
/

-- Medicamentos
DECLARE
    V_NM_MEDICAMENTO VARCHAR2(200) := 'Apoquel 16mg';
    V_DS_DOSAGEM     VARCHAR2(100) := '1 comprimido';
    V_DS_FREQUENCIA  VARCHAR2(100) := '1x ao dia';
    V_DT_INICIO      DATE          := TO_DATE ('10/01/2025', 'DD/MM/YYYY');
    V_DT_FIM         DATE          := TO_DATE ('10/02/2025', 'DD/MM/YYYY');
    V_ID_EVENTO      NUMBER        := 6;
BEGIN
    PRC_INSERT_MEDICAMENTO(V_NM_MEDICAMENTO, V_DS_DOSAGEM, V_DS_FREQUENCIA, V_DT_INICIO, V_DT_FIM, V_ID_EVENTO);
END;
/

DECLARE
    V_NM_MEDICAMENTO VARCHAR2(200) := 'Apoquel 16mg';
    V_DS_DOSAGEM     VARCHAR2(100) := '3 comprimido';
    V_DS_FREQUENCIA  VARCHAR2(100) := '2x ao dia';
    V_DT_INICIO      DATE          := TO_DATE ('10/01/2025', 'DD/MM/YYYY');
    V_DT_FIM         DATE          := TO_DATE ('10/02/2025', 'DD/MM/YYYY');
    V_ID_EVENTO      NUMBER        := 2;
BEGIN
    PRC_INSERT_MEDICAMENTO(V_NM_MEDICAMENTO, V_DS_DOSAGEM, V_DS_FREQUENCIA, V_DT_INICIO, V_DT_FIM, V_ID_EVENTO);
END;
/

DECLARE
    V_NM_MEDICAMENTO VARCHAR2(200) := 'Prednisolona';
    V_DS_DOSAGEM     VARCHAR2(100) := '1 comprimido';
    V_DS_FREQUENCIA  VARCHAR2(100) := '2x ao dia';
    V_DT_INICIO      DATE          := TO_DATE ('15/02/2025', 'DD/MM/YYYY');
    V_DT_FIM         DATE          := TO_DATE ('15/03/2025', 'DD/MM/YYYY');
    V_ID_EVENTO      NUMBER        := 3;
BEGIN
    PRC_INSERT_MEDICAMENTO(V_NM_MEDICAMENTO, V_DS_DOSAGEM, V_DS_FREQUENCIA, V_DT_INICIO, V_DT_FIM, V_ID_EVENTO);
END;
/

DECLARE
    V_NM_MEDICAMENTO VARCHAR2(200) := 'Royal Canin';
    V_DS_DOSAGEM     VARCHAR2(100) := '1 sachê';
    V_DS_FREQUENCIA  VARCHAR2(100) := '2x ao dia';
    V_DT_INICIO      DATE          := TO_DATE ('20/01/2025', 'DD/MM/YYYY');
    V_DT_FIM         DATE          := TO_DATE ('27/01/2025', 'DD/MM/YYYY');
    V_ID_EVENTO      NUMBER        := 4;
BEGIN
    PRC_INSERT_MEDICAMENTO(V_NM_MEDICAMENTO, V_DS_DOSAGEM, V_DS_FREQUENCIA, V_DT_INICIO, V_DT_FIM, V_ID_EVENTO);
END;
/

DECLARE
    V_NM_MEDICAMENTO VARCHAR2(200) := 'Vermífugo Plus';
    V_DS_DOSAGEM     VARCHAR2(100) := '1 comprimido';
    V_DS_FREQUENCIA  VARCHAR2(100) := 'dose única';
    V_DT_INICIO      DATE          := TO_DATE ('05/03/2025', 'DD/MM/YYYY');
    V_DT_FIM         DATE          := TO_DATE ('05/03/2025', 'DD/MM/YYYY');
    V_ID_EVENTO      NUMBER        := 1;
BEGIN
    PRC_INSERT_MEDICAMENTO(V_NM_MEDICAMENTO, V_DS_DOSAGEM, V_DS_FREQUENCIA, V_DT_INICIO, V_DT_FIM, V_ID_EVENTO);
END;
/

DECLARE
    V_NM_MEDICAMENTO VARCHAR2(200) := 'Tramadol';
    V_DS_DOSAGEM     VARCHAR2(100) := '1 comprimido';
    V_DS_FREQUENCIA  VARCHAR2(100) := '3x ao dia';
    V_DT_INICIO      DATE          := TO_DATE ('28/02/2025', 'DD/MM/YYYY');
    V_DT_FIM         DATE          := TO_DATE ('05/03/2025', 'DD/MM/YYYY');
    V_ID_EVENTO      NUMBER        := 5;
BEGIN
    PRC_INSERT_MEDICAMENTO(V_NM_MEDICAMENTO, V_DS_DOSAGEM, V_DS_FREQUENCIA, V_DT_INICIO, V_DT_FIM, V_ID_EVENTO);
END;
/

-- Adesão Medicamentosa
DECLARE
    V_DT_DOSE        DATE          := TO_DATE ('11/01/2025', 'DD/MM/YYYY');
    V_ST_TOMOU       CHAR(1)       := 'S';
    V_DS_OBSERVACAO  VARCHAR2(500) := NULL;
    V_ID_MEDICAMENTO NUMBER        := 1;
BEGIN
    PRC_INSERT_ADESAO_MEDICAMENTO(V_DT_DOSE, V_ST_TOMOU, V_DS_OBSERVACAO, V_ID_MEDICAMENTO);
END;
/

DECLARE
    V_DT_DOSE        DATE          := TO_DATE ('12/01/2025', 'DD/MM/YYYY');
    V_ST_TOMOU       CHAR(1)       := 'S';
    V_DS_OBSERVACAO  VARCHAR2(500) := NULL;
    V_ID_MEDICAMENTO NUMBER        := 2;
BEGIN
    PRC_INSERT_ADESAO_MEDICAMENTO(V_DT_DOSE, V_ST_TOMOU, V_DS_OBSERVACAO, V_ID_MEDICAMENTO);
END;
/

DECLARE
    V_DT_DOSE        DATE          := TO_DATE ('13/01/2025', 'DD/MM/YYYY');
    V_ST_TOMOU       CHAR(1)       := 'N';
    V_DS_OBSERVACAO  VARCHAR2(500) := 'Tutor esqueceu';
    V_ID_MEDICAMENTO NUMBER        := 3;
BEGIN
    PRC_INSERT_ADESAO_MEDICAMENTO(V_DT_DOSE, V_ST_TOMOU, V_DS_OBSERVACAO, V_ID_MEDICAMENTO);
END;
/

DECLARE
    V_DT_DOSE        DATE          := TO_DATE ('16/02/2025', 'DD/MM/YYYY');
    V_ST_TOMOU       CHAR(1)       := 'S';
    V_DS_OBSERVACAO  VARCHAR2(500) := NULL;
    V_ID_MEDICAMENTO NUMBER        := 4;
BEGIN
    PRC_INSERT_ADESAO_MEDICAMENTO(V_DT_DOSE, V_ST_TOMOU, V_DS_OBSERVACAO, V_ID_MEDICAMENTO);
END;
/

DECLARE
    V_DT_DOSE        DATE          := TO_DATE ('17/02/2025', 'DD/MM/YYYY');
    V_ST_TOMOU       CHAR(1)       := 'S';
    V_DS_OBSERVACAO  VARCHAR2(500) := NULL;
    V_ID_MEDICAMENTO NUMBER        := 5;
BEGIN
    PRC_INSERT_ADESAO_MEDICAMENTO(V_DT_DOSE, V_ST_TOMOU, V_DS_OBSERVACAO, V_ID_MEDICAMENTO);
END;
/

DECLARE
    V_DT_DOSE        DATE          := TO_DATE ('21/02/2025', 'DD/MM/YYYY');
    V_ST_TOMOU       CHAR(1)       := 'S';
    V_DS_OBSERVACAO  VARCHAR2(500) := NULL;
    V_ID_MEDICAMENTO NUMBER        := 6;
BEGIN
    PRC_INSERT_ADESAO_MEDICAMENTO(V_DT_DOSE, V_ST_TOMOU, V_DS_OBSERVACAO, V_ID_MEDICAMENTO);
END;
/

-- Notificações
DECLARE 
    V_TP_NOTIFICACAO VARCHAR2(50)   := 'LEMBRETE';
    V_DS_TITULO      VARCHAR2(200)  := 'Vacina do Bob';
    V_DS_MENSAGEM    VARCHAR2(2000) := 'Lembrete: vacina V10 do Bob vence em 30 dias';
    V_ST_LIDA        CHAR(1)        := 'N';
    V_ID_TUTOR       NUMBER         := 1;
    V_ID_PET         NUMBER         := 3;     
BEGIN 
    PRC_INSERT_NOTIFICACAO(V_TP_NOTIFICACAO, V_DS_TITULO, V_DS_MENSAGEM, V_ST_LIDA, V_ID_TUTOR, V_ID_PET);
END;
/

DECLARE
    V_TP_NOTIFICACAO VARCHAR2(50)   := 'ALERTA';
    V_DS_TITULO      VARCHAR2(200)  := 'Febre detectada - Luna';
    V_DS_MENSAGEM    VARCHAR2(2000) := 'Collar detectou temperatura acima do normal';
    V_ST_LIDA        CHAR(1)        := 'N';
    V_ID_TUTOR       NUMBER         := 2;
    V_ID_PET         NUMBER         := 2;
BEGIN
    PRC_INSERT_NOTIFICACAO(V_TP_NOTIFICACAO, V_DS_TITULO, V_DS_MENSAGEM, V_ST_LIDA, V_ID_TUTOR, V_ID_PET);
END;
/

DECLARE
    V_TP_NOTIFICACAO VARCHAR2(50)   := 'URGENTE';
    V_DS_TITULO      VARCHAR2(200)  := 'Medicamento nao administrado - Bob';
    V_DS_MENSAGEM    VARCHAR2(2000) := 'Dose do Tramadol nao confirmada hoje';
    V_ST_LIDA        CHAR(1)        := 'N';
    V_ID_TUTOR       NUMBER         := 1;
    V_ID_PET         NUMBER         := 3;
BEGIN
    PRC_INSERT_NOTIFICACAO(V_TP_NOTIFICACAO, V_DS_TITULO, V_DS_MENSAGEM, V_ST_LIDA, V_ID_TUTOR, V_ID_PET);
END;
/

DECLARE
    V_TP_NOTIFICACAO VARCHAR2(50)   := 'INFO';
    V_DS_TITULO      VARCHAR2(200)  := 'Consulta realizada - Nina';
    V_DS_MENSAGEM    VARCHAR2(2000) := 'Consulta de castração realizada com sucesso';
    V_ST_LIDA        CHAR(1)        := 'S';
    V_ID_TUTOR       NUMBER         := 2;
    V_ID_PET         NUMBER         := 4;
BEGIN
    PRC_INSERT_NOTIFICACAO(V_TP_NOTIFICACAO, V_DS_TITULO, V_DS_MENSAGEM, V_ST_LIDA, V_ID_TUTOR, V_ID_PET);
END;
/

DECLARE
    V_TP_NOTIFICACAO VARCHAR2(50)   := 'LEMBRETE';
    V_DS_TITULO      VARCHAR2(200)  := 'Antipulga atrasado - Nina';
    V_DS_MENSAGEM    VARCHAR2(2000) := 'Aplicacao do Frontline esta atrasada';
    V_ST_LIDA        CHAR(1)        := 'N';
    V_ID_TUTOR       NUMBER         := 2;
    V_ID_PET         NUMBER         := 4;
BEGIN
    PRC_INSERT_NOTIFICACAO(V_TP_NOTIFICACAO, V_DS_TITULO, V_DS_MENSAGEM, V_ST_LIDA, V_ID_TUTOR, V_ID_PET);
END;
/

-- Health Score
DECLARE 
    V_NR_SCORE NUMBER        := 75; 
    V_DS_OBS   VARCHAR2(500) := 'Score inicial';
    V_ID_PET   NUMBER        := 1;
BEGIN 
    PRC_INSERT_SCORE_HISTORICO(V_NR_SCORE, V_DS_OBS, V_ID_PET); 
END;
/

DECLARE 
    V_NR_SCORE NUMBER        := 72; 
    V_DS_OBS   VARCHAR2(500) := 'Leve queda'; 
    V_ID_PET   NUMBER        := 1;
BEGIN 
    PRC_INSERT_SCORE_HISTORICO(V_NR_SCORE, V_DS_OBS, V_ID_PET); 
END;
/

DECLARE 
    V_NR_SCORE NUMBER        := 68; 
    V_DS_OBS   VARCHAR2(500) := 'Dermatite ativa'; 
    V_ID_PET   NUMBER        := 1;
BEGIN 
    PRC_INSERT_SCORE_HISTORICO(V_NR_SCORE, V_DS_OBS, V_ID_PET); 
END;
/

DECLARE 
    V_NR_SCORE NUMBER        := 70; 
    V_DS_OBS   VARCHAR2(500) := 'Medicamento iniciado'; 
    V_ID_PET   NUMBER        := 1;
BEGIN 
    PRC_INSERT_SCORE_HISTORICO(V_NR_SCORE, V_DS_OBS, V_ID_PET); 
END;
/

DECLARE 
    V_NR_SCORE NUMBER        := 78; 
    V_DS_OBS   VARCHAR2(500) := 'Melhora significativa'; 
    V_ID_PET   NUMBER        := 1;
BEGIN 
    PRC_INSERT_SCORE_HISTORICO(V_NR_SCORE, V_DS_OBS, V_ID_PET); 
END;
/

DECLARE 
    V_NR_SCORE NUMBER        := 82; 
    V_DS_OBS   VARCHAR2(500) := 'Recuperado'; 
    V_ID_PET   NUMBER        := 1;
BEGIN 
    PRC_INSERT_SCORE_HISTORICO(V_NR_SCORE, V_DS_OBS, V_ID_PET); 
END;
/

DECLARE 
    V_NR_SCORE NUMBER        := 60; 
    V_DS_OBS   VARCHAR2(500) := 'Score inicial'; 
    V_ID_PET   NUMBER        := 2;
BEGIN 
    PRC_INSERT_SCORE_HISTORICO(V_NR_SCORE, V_DS_OBS, V_ID_PET); 
END;
/

DECLARE 
    V_NR_SCORE NUMBER        := 55; 
    V_DS_OBS   VARCHAR2(500) := 'Obesidade detectada'; 
    V_ID_PET   NUMBER        := 2;
BEGIN 
    PRC_INSERT_SCORE_HISTORICO(V_NR_SCORE, V_DS_OBS, V_ID_PET); 
END;
/

DECLARE 
    V_NR_SCORE NUMBER        := 50; 
    V_DS_OBS   VARCHAR2(500) := 'Dieta iniciada'; 
    V_ID_PET   NUMBER        := 2;
BEGIN 
    PRC_INSERT_SCORE_HISTORICO(V_NR_SCORE, V_DS_OBS, V_ID_PET); 
END;
/

DECLARE 
    V_NR_SCORE NUMBER        := 53; 
    V_DS_OBS   VARCHAR2(500) := 'Leve melhora'; 
    V_ID_PET   NUMBER        := 2;
BEGIN 
    PRC_INSERT_SCORE_HISTORICO(V_NR_SCORE, V_DS_OBS, V_ID_PET); 
END;
/

DECLARE 
    V_NR_SCORE NUMBER        := 58; 
    V_DS_OBS   VARCHAR2(500) := 'Perdendo peso'; 
    V_ID_PET   NUMBER        := 2;
BEGIN 
    PRC_INSERT_SCORE_HISTORICO(V_NR_SCORE, V_DS_OBS, V_ID_PET); 
END;
/

DECLARE 
    V_NR_SCORE NUMBER        := 63; 
    V_DS_OBS   VARCHAR2(500) := 'Evoluindo bem'; 
    V_ID_PET   NUMBER        := 2;
BEGIN 
    PRC_INSERT_SCORE_HISTORICO(V_NR_SCORE, V_DS_OBS, V_ID_PET); 
END;
/

DECLARE 
    V_NR_SCORE NUMBER        := 80; 
    V_DS_OBS   VARCHAR2(500) := 'Score inicial'; 
    V_ID_PET   NUMBER        := 3;
BEGIN 
    PRC_INSERT_SCORE_HISTORICO(V_NR_SCORE, V_DS_OBS, V_ID_PET); 
END;
/

DECLARE 
    V_NR_SCORE NUMBER        := 78; 
    V_DS_OBS   VARCHAR2(500) := 'Estavel';
    V_ID_PET   NUMBER        := 3;
BEGIN 
    PRC_INSERT_SCORE_HISTORICO(V_NR_SCORE, V_DS_OBS, V_ID_PET); 
END;
/

DECLARE 
    V_NR_SCORE NUMBER        := 75; 
    V_DS_OBS   VARCHAR2(500) := 'Pre cirurgia'; 
    V_ID_PET   NUMBER        := 3;
BEGIN 
    PRC_INSERT_SCORE_HISTORICO(V_NR_SCORE, V_DS_OBS, V_ID_PET); 
END;
/

DECLARE 
    V_NR_SCORE NUMBER        := 65; 
    V_DS_OBS   VARCHAR2(500) := 'Pos cirurgia'; 
    V_ID_PET   NUMBER        := 3;
BEGIN 
    PRC_INSERT_SCORE_HISTORICO(V_NR_SCORE, V_DS_OBS, V_ID_PET); 
END;
/

DECLARE 
    V_NR_SCORE NUMBER        := 72; 
    V_DS_OBS   VARCHAR2(500) := 'Recuperando'; 
    V_ID_PET   NUMBER        := 3;
BEGIN 
    PRC_INSERT_SCORE_HISTORICO(V_NR_SCORE, V_DS_OBS, V_ID_PET); 
END;
/

DECLARE 
    V_NR_SCORE NUMBER        := 79; 
    V_DS_OBS   VARCHAR2(500) := 'Recuperado'; 
    V_ID_PET   NUMBER        := 3;
BEGIN 
    PRC_INSERT_SCORE_HISTORICO(V_NR_SCORE, V_DS_OBS, V_ID_PET); 
END;
/

DECLARE 
    V_NR_SCORE NUMBER        := 35; 
    V_DS_OBS   VARCHAR2(500) := 'Score inicial critico'; 
    V_ID_PET   NUMBER        := 4;
BEGIN 
    PRC_INSERT_SCORE_HISTORICO(V_NR_SCORE, V_DS_OBS, V_ID_PET); 
END;
/

DECLARE 
    V_NR_SCORE NUMBER        := 38; 
    V_DS_OBS   VARCHAR2(500) := 'Leve melhora'; 
    V_ID_PET   NUMBER        := 4;
BEGIN 
    PRC_INSERT_SCORE_HISTORICO(V_NR_SCORE, V_DS_OBS, V_ID_PET); 
END;
/

DECLARE 
    V_NR_SCORE NUMBER        := 45;
    V_DS_OBS   VARCHAR2(500) := 'Tratamento iniciado';
    V_ID_PET   NUMBER        := 4;
BEGIN 
    PRC_INSERT_SCORE_HISTORICO(V_NR_SCORE, V_DS_OBS, V_ID_PET); 
END;
/

DECLARE 
    V_NR_SCORE NUMBER        := 50;
    V_DS_OBS   VARCHAR2(500) := 'Evoluindo'; 
    V_ID_PET   NUMBER        := 4;
BEGIN 
    PRC_INSERT_SCORE_HISTORICO(V_NR_SCORE, V_DS_OBS, V_ID_PET); 
END;
/

DECLARE 
    V_NR_SCORE NUMBER        := 58; 
    V_DS_OBS   VARCHAR2(500) := 'Boa evolucao'; 
    V_ID_PET   NUMBER        := 4;
BEGIN 
    PRC_INSERT_SCORE_HISTORICO(V_NR_SCORE, V_DS_OBS, V_ID_PET); 
END;
/

DECLARE 
    V_NR_SCORE NUMBER        := 65; 
    V_DS_OBS   VARCHAR2(500) := 'Estavel'; 
    V_ID_PET   NUMBER        := 4;
BEGIN 
    PRC_INSERT_SCORE_HISTORICO(V_NR_SCORE, V_DS_OBS, V_ID_PET); 
END;
/

DECLARE 
    V_NR_SCORE NUMBER        := 90; 
    V_DS_OBS   VARCHAR2(500) := 'Score inicial'; 
    V_ID_PET   NUMBER        := 5;
BEGIN 
    PRC_INSERT_SCORE_HISTORICO(V_NR_SCORE, V_DS_OBS, V_ID_PET); 
END;
/

DECLARE 
    V_NR_SCORE NUMBER        := 88; 
    V_DS_OBS   VARCHAR2(500) := 'Estavel';
    V_ID_PET   NUMBER        := 5;
BEGIN 
    PRC_INSERT_SCORE_HISTORICO(V_NR_SCORE, V_DS_OBS, V_ID_PET); 
END;
/

DECLARE 
    V_NR_SCORE NUMBER        := 85; 
    V_DS_OBS   VARCHAR2(500) := 'Leve queda'; 
    V_ID_PET   NUMBER        := 5;
BEGIN 
    PRC_INSERT_SCORE_HISTORICO(V_NR_SCORE, V_DS_OBS, V_ID_PET); 
END;
/

DECLARE 
    V_NR_SCORE NUMBER        := 87;
    V_DS_OBS   VARCHAR2(500) := 'Recuperando';
    V_ID_PET   NUMBER        := 5;
BEGIN 
    PRC_INSERT_SCORE_HISTORICO(V_NR_SCORE, V_DS_OBS, V_ID_PET); 
END;
/

DECLARE 
    V_NR_SCORE NUMBER        := 91; 
    V_DS_OBS   VARCHAR2(500) := 'Otimo'; 
    V_ID_PET   NUMBER        := 5;
BEGIN 
    PRC_INSERT_SCORE_HISTORICO(V_NR_SCORE, V_DS_OBS, V_ID_PET); 
END;
/

DECLARE 
    V_NR_SCORE NUMBER        := 93; 
    V_DS_OBS   VARCHAR2(500) := 'Excelente'; 
    V_ID_PET   NUMBER        := 5;
BEGIN 
    PRC_INSERT_SCORE_HISTORICO(V_NR_SCORE, V_DS_OBS, V_ID_PET); 
END;
/

-- BCS
DECLARE 
    V_NR_BCS    NUMBER         := 5; 
    V_DS_FOTO   VARCHAR2(500)  := 'http://pettrack.com/fotos/thor1.jpg';
    V_DS_OBS    VARCHAR2(1000) := 'BCS ideal';
    V_ID_PET    NUMBER         := 1;
BEGIN 
    PRC_INSERT_BCS_HISTORICO(V_NR_BCS, V_DS_FOTO, V_DS_OBS, V_ID_PET); 
END;
/

DECLARE 
    V_NR_BCS    NUMBER         := 7; 
    V_DS_FOTO   VARCHAR2(500)  := 'http://pettrack.com/fotos/luna1.jpg';
    V_DS_OBS    VARCHAR2(1000) := 'Acima do ideal';
    V_ID_PET    NUMBER         := 2;
BEGIN 
    PRC_INSERT_BCS_HISTORICO(V_NR_BCS, V_DS_FOTO, V_DS_OBS, V_ID_PET); 
END;
/

DECLARE 
    V_NR_BCS    NUMBER         := 4; 
    V_DS_FOTO   VARCHAR2(500)  := 'http://pettrack.com/fotos/bob1.jpg';
    V_DS_OBS    VARCHAR2(1000) := 'Levemente abaixo'; 
    V_ID_PET    NUMBER         := 3;
BEGIN 
    PRC_INSERT_BCS_HISTORICO(V_NR_BCS, V_DS_FOTO, V_DS_OBS, V_ID_PET); 
END;
/

DECLARE 
    V_NR_BCS    NUMBER         := 3; 
    V_DS_FOTO   VARCHAR2(500)  := 'http://pettrack.com/fotos/nina1.jpg';
    V_DS_OBS    VARCHAR2(1000) := 'Abaixo do ideal';  
    V_ID_PET    NUMBER         := 4;
BEGIN 
    PRC_INSERT_BCS_HISTORICO(V_NR_BCS, V_DS_FOTO, V_DS_OBS, V_ID_PET); 
END;
/

DECLARE 
    V_NR_BCS    NUMBER         := 5; 
    V_DS_FOTO   VARCHAR2(500)  := 'http://pettrack.com/fotos/max1.jpg';    
    V_DS_OBS    VARCHAR2(1000) := 'BCS ideal';        
    V_ID_PET    NUMBER         := 5;
BEGIN 
    PRC_INSERT_BCS_HISTORICO(V_NR_BCS, V_DS_FOTO, V_DS_OBS, V_ID_PET); 
END;
/

-- Collar Leitura
DECLARE 
    V_NR_TEMP  NUMBER        := 38.5; 
    V_NR_ATIVI NUMBER        := 120; 
    V_DS_MQTT  VARCHAR2(200) := 'pettrack/collar/pet1'; 
    V_ID_PET   NUMBER        := 1;
BEGIN 
    PRC_INSERT_COLLAR_LEITURA(V_NR_TEMP, V_NR_ATIVI, V_DS_MQTT, V_ID_PET); 
END;
/

DECLARE 
    V_NR_TEMP  NUMBER        := 39.8; 
    V_NR_ATIVI NUMBER        := 30;  
    V_DS_MQTT  VARCHAR2(200) := 'pettrack/collar/pet2'; 
    V_ID_PET   NUMBER        := 2;
BEGIN 
    PRC_INSERT_COLLAR_LEITURA(V_NR_TEMP, V_NR_ATIVI, V_DS_MQTT, V_ID_PET); 
END;
/

DECLARE 
    V_NR_TEMP  NUMBER        := 38.2; 
    V_NR_ATIVI NUMBER        := 95;  
    V_DS_MQTT  VARCHAR2(200) := 'pettrack/collar/pet3'; 
    V_ID_PET   NUMBER        := 3;
BEGIN 
    PRC_INSERT_COLLAR_LEITURA(V_NR_TEMP, V_NR_ATIVI, V_DS_MQTT, V_ID_PET); 
END;
/

DECLARE 
    V_NR_TEMP  NUMBER        := 40.1; 
    V_NR_ATIVI NUMBER        := 10; 
    V_DS_MQTT  VARCHAR2(200) := 'pettrack/collar/pet4'; 
    V_ID_PET   NUMBER        := 4;
BEGIN 
    PRC_INSERT_COLLAR_LEITURA(V_NR_TEMP, V_NR_ATIVI, V_DS_MQTT, V_ID_PET); 
END;
/

DECLARE 
    V_NR_TEMP  NUMBER        := 38.0; 
    V_NR_ATIVI NUMBER        := 200; 
    V_DS_MQTT  VARCHAR2(200) := 'pettrack/collar/pet5'; 
    V_ID_PET   NUMBER        := 5;
BEGIN 
    PRC_INSERT_COLLAR_LEITURA(V_NR_TEMP, V_NR_ATIVI, V_DS_MQTT, V_ID_PET); 
END;
/

-- Alertas
DECLARE 
    V_TP VARCHAR2(50)   := 'FEBRE';        
    V_DS VARCHAR2(1000) := 'Temperatura acima de 39.5C';     
    V_VL NUMBER         := 39.8; 
    V_ST CHAR(1)        := 'N'; 
    V_ID NUMBER         := 3;
BEGIN 
    PRC_INSERT_ALERTA(V_TP, V_DS, V_VL, V_ST, V_ID); 
END;
/

DECLARE 
    V_TP VARCHAR2(50)   := 'SEDENTARISMO'; 
    V_DS VARCHAR2(1000) := 'Atividade abaixo do esperado';   
    V_VL NUMBER         := 10;   
    V_ST CHAR(1)        := 'N'; 
    V_ID NUMBER         := 4;
BEGIN 
    PRC_INSERT_ALERTA(V_TP, V_DS, V_VL, V_ST, V_ID); 
END;
/

DECLARE 
    V_TP VARCHAR2(50)   := 'BCS_CRITICO';  
    V_DS VARCHAR2(1000) := 'BCS abaixo do ideal';            
    V_VL NUMBER         := 3;    
    V_ST CHAR(1)        := 'N'; 
    V_ID NUMBER         := 4;
BEGIN 
    PRC_INSERT_ALERTA(V_TP, V_DS, V_VL, V_ST, V_ID); 
END;
/

DECLARE 
    V_TP VARCHAR2(50)   := 'ADESAO';       
    V_DS VARCHAR2(1000) := 'Dose nao confirmada pelo tutor'; 
    V_VL NUMBER         := NULL; 
    V_ST CHAR(1)        := 'S'; 
    V_ID NUMBER         := 4;
BEGIN 
    PRC_INSERT_ALERTA(V_TP, V_DS, V_VL, V_ST, V_ID); 
END;
/

DECLARE 
    V_TP VARCHAR2(50)   := 'FEBRE';        
    V_DS VARCHAR2(1000) := 'Temperatura elevada detectada';  
    V_VL NUMBER         := 40.1; 
    V_ST CHAR(1)        := 'N'; 
    V_ID NUMBER         := 4;
BEGIN 
    PRC_INSERT_ALERTA(V_TP, V_DS, V_VL, V_ST, V_ID); 
END;
/

-- =============================================================================
-- 6. BLOCOS ANÔNIMOS ANALÍTICOS (CONSULTAS, JOINS, LAG/LEAD E CURSORES)
-- =============================================================================

-- BLOCO 1: Média de Health Score agrupada por Clínica
BEGIN
    DBMS_OUTPUT.PUT_LINE('========================================');
    DBMS_OUTPUT.PUT_LINE('MEDIA DE HEALTH SCORE POR CLINICA');
    DBMS_OUTPUT.PUT_LINE('========================================');
    FOR REGISTRO IN (
        SELECT
            TB_CLINICA.NM_CLINICA AS NOME,
            COUNT(DISTINCT TB_PET.ID_PET) AS PETS,
            ROUND(AVG(TB_SCORE_HISTORICO.NR_SCORE), 2) AS MEDIA
        FROM TB_CLINICA 
        JOIN TB_PET
            ON TB_PET.ID_CLINICA = TB_CLINICA.ID_CLINICA
        JOIN TB_SCORE_HISTORICO
            ON TB_SCORE_HISTORICO.ID_PET = TB_PET.ID_PET 
        JOIN TB_TUTOR 
            ON TB_TUTOR.ID_TUTOR = TB_PET.ID_TUTOR
        GROUP BY TB_CLINICA.NM_CLINICA
        ORDER BY MEDIA DESC
    ) LOOP 
        DBMS_OUTPUT.PUT_LINE('Clinica: ' || REGISTRO.NOME);
        DBMS_OUTPUT.PUT_LINE('Quantidade de pets:' || REGISTRO.PETS);
        DBMS_OUTPUT.PUT_LINE('Média de score: ' || REGISTRO.MEDIA);
    END LOOP;
END;
/

-- BLOCO 2: Totalização de alertas críticos nos últimos 30 dias por pet e tutor
BEGIN
    DBMS_OUTPUT.PUT_LINE('========================================');
    DBMS_OUTPUT.PUT_LINE('ALERTAS POR TIPO NOS ULTIMOS 30 DIAS');
    DBMS_OUTPUT.PUT_LINE('========================================');
    FOR REGISTRO IN (
        SELECT
            TB_ALERTA.TP_ALERTA                AS TIPO,
            TB_PET.NM_PET                      AS PET,
            TB_TUTOR.NM_TUTOR                  AS TUTOR,
            COUNT(TB_ALERTA.ID_ALERTA)         AS QT_ALERTAS
        FROM TB_ALERTA
        JOIN TB_PET
            ON TB_PET.ID_PET = TB_ALERTA.ID_PET
        JOIN TB_TUTOR
            ON TB_TUTOR.ID_TUTOR = TB_PET.ID_TUTOR
        JOIN TB_CLINICA
            ON TB_CLINICA.ID_CLINICA = TB_PET.ID_CLINICA
        WHERE TB_ALERTA.DT_ALERTA >= SYSDATE - 30
        GROUP BY TB_ALERTA.TP_ALERTA, TB_PET.NM_PET, TB_TUTOR.NM_TUTOR
        ORDER BY QT_ALERTAS DESC
    ) LOOP
        DBMS_OUTPUT.PUT_LINE(
            'Tipo: '      || REGISTRO.TIPO      ||
            ' | Pet: '    || REGISTRO.PET       ||
            ' | Tutor: '  || REGISTRO.TUTOR     ||
            ' | Qtd: '    || REGISTRO.QT_ALERTAS
        );
    END LOOP;
END;
/

-- BLOCO 3: Rastreamento de adesão medicamentosa por tutor e medicamento
BEGIN
    DBMS_OUTPUT.PUT_LINE('========================================');
    DBMS_OUTPUT.PUT_LINE('ADESAO MEDICAMENTOSA POR TUTOR');
    DBMS_OUTPUT.PUT_LINE('========================================');
    FOR REGISTRO IN (
        SELECT
            TB_TUTOR.NM_TUTOR AS TUTOR,
            TB_PET.NM_PET AS PET,
            TB_MEDICAMENTO.NM_MEDICAMENTO AS MEDICAMENTO,
            TB_ADESAO_MEDICAMENTO.ST_TOMOU AS TOMOU
        FROM TB_TUTOR 
        JOIN TB_PET 
            ON TB_PET.ID_TUTOR = TB_TUTOR.ID_TUTOR
        JOIN TB_EVENTO_CLINICO
            ON TB_EVENTO_CLINICO.ID_PET = TB_PET.ID_PET
        JOIN TB_MEDICAMENTO 
            ON TB_MEDICAMENTO.ID_EVENTO = TB_EVENTO_CLINICO.ID_EVENTO
        JOIN TB_ADESAO_MEDICAMENTO 
            ON TB_ADESAO_MEDICAMENTO.ID_MEDICAMENTO = TB_MEDICAMENTO.ID_MEDICAMENTO
        GROUP BY TB_TUTOR.NM_TUTOR, TB_PET.NM_PET, TB_MEDICAMENTO.NM_MEDICAMENTO, TB_ADESAO_MEDICAMENTO.ST_TOMOU
        ORDER BY TB_TUTOR.NM_TUTOR, TB_PET.NM_PET
    ) LOOP
        DBMS_OUTPUT.PUT_LINE('Tutor: '       || REGISTRO.TUTOR);
        DBMS_OUTPUT.PUT_LINE('Pet: '         || REGISTRO.PET);
        DBMS_OUTPUT.PUT_LINE('Medicamento: ' || REGISTRO.MEDICAMENTO);
        DBMS_OUTPUT.PUT_LINE('Tomou: '       || REGISTRO.TOMOU);
    END LOOP;
END;
/

-- BLOCO 4: Funções Analíticas LAG/LEAD
BEGIN
    DBMS_OUTPUT.PUT_LINE('========================================');
    DBMS_OUTPUT.PUT_LINE('EVOLUCAO DO HEALTH SCORE POR PET');
    DBMS_OUTPUT.PUT_LINE('========================================');
    FOR REGISTRO IN (
        SELECT
            TB_PET.NM_PET AS PET,
            TB_SCORE_HISTORICO.NR_SCORE AS SCORE_ATUAL,
            NVL(TO_CHAR(LAG(TB_SCORE_HISTORICO.NR_SCORE)
                OVER (
                PARTITION BY TB_SCORE_HISTORICO.ID_PET
                      ORDER BY TB_SCORE_HISTORICO.DT_REGISTRO)), 'Vazio') AS SCORE_ANTERIOR,
            NVL(TO_CHAR(LEAD(TB_SCORE_HISTORICO.NR_SCORE)
                OVER (
                PARTITION BY TB_SCORE_HISTORICO.ID_PET 
                ORDER BY TB_SCORE_HISTORICO.DT_REGISTRO)), 'Vazio') AS PROXIMO_SCORE
        FROM TB_PET
        JOIN TB_SCORE_HISTORICO
            ON TB_SCORE_HISTORICO.ID_PET = TB_PET.ID_PET
        ORDER BY TB_PET.NM_PET
    ) LOOP
        DBMS_OUTPUT.PUT_LINE('Pet: ' || REGISTRO.PET || ' | Anterior: ' || REGISTRO.SCORE_ANTERIOR|| ' | Atual: ' || REGISTRO.SCORE_ATUAL || ' | Proximo: ' || REGISTRO.PROXIMO_SCORE);
    END LOOP;
END;
/

-- BLOCO 5: Cursor Explícito com Sumarização
DECLARE
    CURSOR C_EXIBE IS
        SELECT 
            TB_SCORE_HISTORICO.NR_SCORE AS NOTA,
            TB_PET.NM_PET AS PET
        FROM TB_SCORE_HISTORICO
        JOIN TB_PET
            ON TB_PET.ID_PET = TB_SCORE_HISTORICO.ID_PET
        ORDER BY TB_PET.NM_PET;
        
    V_MENOR_40    NUMBER := 0;
    V_ENTRE_40_70 NUMBER := 0;
    V_MAIOR_70    NUMBER := 0;
BEGIN
    FOR V_EXIBE IN C_EXIBE LOOP
        DBMS_OUTPUT.PUT_LINE('Resgistros de score de pets: ' || 'Pet: ' || V_EXIBE.PET || '  | SCORE: ' || V_EXIBE.NOTA);
        IF V_EXIBE.NOTA < 40 THEN
            V_MENOR_40 := V_MENOR_40 + 1;
        ELSIF V_EXIBE.NOTA >= 40 AND V_EXIBE.NOTA < 70 THEN
            V_ENTRE_40_70 := V_ENTRE_40_70 + 1;
        ELSE
            V_MAIOR_70 := V_MAIOR_70 + 1;
        END IF;
    END LOOP;
    DBMS_OUTPUT.PUT_LINE('===========================================');
    DBMS_OUTPUT.PUT_LINE('SUMARIZACAO:');
    DBMS_OUTPUT.PUT_LINE('Score < 40    : ' || V_MENOR_40);
    DBMS_OUTPUT.PUT_LINE('Score 40 a 70 : ' || V_ENTRE_40_70);
    DBMS_OUTPUT.PUT_LINE('Score > 70    : ' || V_MAIOR_70);
END;
/

-- BLOCO 6: Cursor Explícito com Condicional para Febre
DECLARE
    CURSOR C_CURSOR IS
        SELECT 
            TB_ALERTA.TP_ALERTA,
            TB_PET.NM_PET AS PET
        FROM TB_ALERTA
        JOIN TB_PET
            ON TB_PET.ID_PET = TB_ALERTA.ID_PET
        ORDER BY TP_ALERTA;
BEGIN
    FOR V_EXIBE IN C_CURSOR LOOP
        DBMS_OUTPUT.PUT_LINE('===========================================');
        DBMS_OUTPUT.PUT_LINE('Tipos de alertas');
        DBMS_OUTPUT.PUT_LINE('Alerta do tipo: ' || V_EXIBE.TP_ALERTA);
        IF (UPPER(V_EXIBE.TP_ALERTA) LIKE 'FEBRE') THEN
            DBMS_OUTPUT.PUT_LINE('===========================================');
            DBMS_OUTPUT.PUT_LINE('Este pet precisa de atenção: '|| V_EXIBE.PET);
            DBMS_OUTPUT.PUT_LINE('Alerta do tipo: ' || V_EXIBE.TP_ALERTA);
        END IF;
    END LOOP;
END;
/

-- BLOCO 7: Cursor Explícito para Protocolos Pendentes
DECLARE
    CURSOR C_CURSOR IS
        SELECT 
            TB_PROTOCOLO_PREVENTIVO.ST_STATUS AS STATUS,
            TB_PET.NM_PET AS PET
        FROM TB_PROTOCOLO_PREVENTIVO
        JOIN TB_PET
            ON TB_PET.ID_PET = TB_PROTOCOLO_PREVENTIVO.ID_PET
        ORDER BY TB_PET.NM_PET;
BEGIN
    FOR V_EXIBE IN C_CURSOR LOOP
        DBMS_OUTPUT.PUT_LINE('===========================================');
        DBMS_OUTPUT.PUT_LINE('Protocolos pendentes:');
        IF (UPPER(V_EXIBE.STATUS) LIKE 'PENDENTE') THEN
            DBMS_OUTPUT.PUT_LINE('Pet": ' || V_EXIBE.PET);
            DBMS_OUTPUT.PUT_LINE('Status": ' || V_EXIBE.STATUS);
        END IF;
    END LOOP;
END;
/

-- BLOCO 8: Cursor Explícito para Leituras de Temperatura > 38°C
DECLARE
    CURSOR C_CURSOR IS
        SELECT 
            TB_COLLAR_LEITURA.NR_TEMPERATURA AS TEMPERATURA,
            TB_PET.NM_PET AS PET
        FROM TB_COLLAR_LEITURA
        JOIN TB_PET
            ON TB_PET.ID_PET = TB_COLLAR_LEITURA.ID_PET
        ORDER BY TB_PET.NM_PET;
BEGIN
    FOR V_EXIBE IN C_CURSOR LOOP
        DBMS_OUTPUT.PUT_LINE('===========================================');
        DBMS_OUTPUT.PUT_LINE('Temperaturas de pet acima de 38 Graus:');
        IF (V_EXIBE.TEMPERATURA > 38) THEN
            DBMS_OUTPUT.PUT_LINE('Pet": ' || V_EXIBE.PET);
            DBMS_OUTPUT.PUT_LINE('Temperatura": ' || V_EXIBE.TEMPERATURA);
        END IF;
    END LOOP;
END;
/

-- =============================================================================
-- FIAP - CHALLENGE 2026 | 2º SEMESTRE (SPRINT 3)
-- ENTREGA: 01 Tabela e Trigger de Auditoria, 02 Funções e 02 Procedimentos
-- =============================================================================

CREATE OR REPLACE TRIGGER TRG_AUDITORIA_PET
AFTER INSERT OR UPDATE OR DELETE ON TB_PET
FOR EACH ROW
DECLARE
    V_OPERACAO VARCHAR2(10);
    V_OLD_DATA VARCHAR2(4000);
    V_NEW_DATA VARCHAR2(4000);
BEGIN
    IF INSERTING THEN
        V_OPERACAO := 'INSERT';
        V_OLD_DATA := NULL;
        V_NEW_DATA := 'ID=' || :NEW.ID_PET || 
                      ' | Nome=' || :NEW.NM_PET || 
                      ' | Especie=' || :NEW.DS_ESPECIE || 
                      ' | Raca=' || NVL(:NEW.DS_RACA, 'SRD') || 
                      ' | Sexo=' || :NEW.DS_SEXO || 
                      ' | Idade=' || :NEW.NR_IDADE_ANOS || 
                      ' | Peso=' || :NEW.NR_PESO_KG || 
                      ' | IdTutor=' || :NEW.ID_TUTOR || 
                      ' | IdClinica=' || :NEW.ID_CLINICA;

    ELSIF UPDATING THEN
        V_OPERACAO := 'UPDATE';
        V_OLD_DATA := 'ID=' || :OLD.ID_PET || 
                      ' | Nome=' || :OLD.NM_PET || 
                      ' | Especie=' || :OLD.DS_ESPECIE || 
                      ' | Raca=' || NVL(:OLD.DS_RACA, 'SRD') || 
                      ' | Sexo=' || :OLD.DS_SEXO || 
                      ' | Idade=' || :OLD.NR_IDADE_ANOS || 
                      ' | Peso=' || :OLD.NR_PESO_KG || 
                      ' | IdTutor=' || :OLD.ID_TUTOR || 
                      ' | IdClinica=' || :OLD.ID_CLINICA;
        V_NEW_DATA := 'ID=' || :NEW.ID_PET || 
                      ' | Nome=' || :NEW.NM_PET || 
                      ' | Especie=' || :NEW.DS_ESPECIE || 
                      ' | Raca=' || NVL(:NEW.DS_RACA, 'SRD') || 
                      ' | Sexo=' || :NEW.DS_SEXO || 
                      ' | Idade=' || :NEW.NR_IDADE_ANOS || 
                      ' | Peso=' || :NEW.NR_PESO_KG || 
                      ' | IdTutor=' || :NEW.ID_TUTOR || 
                      ' | IdClinica=' || :NEW.ID_CLINICA;

    ELSIF DELETING THEN
        V_OPERACAO := 'DELETE';
        V_OLD_DATA := 'ID=' || :OLD.ID_PET || 
                      ' | Nome=' || :OLD.NM_PET || 
                      ' | Especie=' || :OLD.DS_ESPECIE || 
                      ' | Raca=' || NVL(:OLD.DS_RACA, 'SRD') || 
                      ' | Sexo=' || :OLD.DS_SEXO || 
                      ' | Idade=' || :OLD.NR_IDADE_ANOS || 
                      ' | Peso=' || :OLD.NR_PESO_KG || 
                      ' | IdTutor=' || :OLD.ID_TUTOR || 
                      ' | IdClinica=' || :OLD.ID_CLINICA;
        V_NEW_DATA := NULL;
    END IF;

    INSERT INTO TB_AUDITORIA_PETTRACK (
        ID_AUDITORIA, NM_TABELA, NM_USUARIO, TP_OPERACAO, DT_OPERACAO, DS_VALORES_ANTERIORES, DS_VALORES_NOVOS
    ) VALUES (
        SEQ_AUDITORIA.NEXTVAL, 'TB_PET', USER, V_OPERACAO, SYSDATE, V_OLD_DATA, V_NEW_DATA
    );
END TRG_AUDITORIA_PET;
/

-- Função 1: JSON Manual com 4 Exceções
CREATE OR REPLACE FUNCTION FN_MONTAR_JSON_PET (
    P_ID_PET     IN NUMBER,
    P_NM_PET     IN VARCHAR2,
    P_ESPECIE    IN VARCHAR2,
    P_RACA       IN VARCHAR2,
    P_PESO       IN NUMBER,
    P_NM_TUTOR   IN VARCHAR2,
    P_NM_CLINICA IN VARCHAR2
) RETURN VARCHAR2
IS
    V_JSON VARCHAR2(4000);
    
    EX_DADOS_OBRIGATORIOS EXCEPTION;
    EX_PESO_INVALIDO      EXCEPTION;
BEGIN
    IF P_ID_PET IS NULL OR P_NM_PET IS NULL OR P_NM_TUTOR IS NULL THEN
        RAISE EX_DADOS_OBRIGATORIOS;
    END IF;

    IF P_PESO IS NOT NULL AND P_PESO <= 0 THEN
        RAISE EX_PESO_INVALIDO;
    END IF;

    V_JSON := '{' ||
                '"idPet": '      || P_ID_PET || ', ' ||
                '"nome": "'      || REPLACE(P_NM_PET, '"', '\"') || '", ' ||
                '"especie": "'   || NVL(P_ESPECIE, 'N/A') || '", ' ||
                '"raca": "'      || NVL(P_RACA, 'SRD') || '", ' ||
                '"pesoKg": '     || NVL(TO_CHAR(P_PESO, 'FM999.00'), 'null') || ', ' ||
                '"tutor": "'     || REPLACE(P_NM_TUTOR, '"', '\"') || '", ' ||
                '"clinica": "'   || REPLACE(NVL(P_NM_CLINICA, 'Não associada'), '"', '\"') || '"' ||
              '}';

    RETURN V_JSON;

EXCEPTION
    WHEN EX_DADOS_OBRIGATORIOS THEN
        PRC_INSERT_LOG_ERRO('FN_MONTAR_JSON_PET', -20001, 'Erro: Identificador do Pet, Nome ou Tutor não informados.');
        RETURN '{"erro": "Dados obrigatorios ausentes"}';

    WHEN EX_PESO_INVALIDO THEN
        PRC_INSERT_LOG_ERRO('FN_MONTAR_JSON_PET', -20002, 'Erro: Peso informado menor ou igual a zero.');
        RETURN '{"erro": "Peso invalido informado"}';

    WHEN VALUE_ERROR THEN
        PRC_INSERT_LOG_ERRO('FN_MONTAR_JSON_PET', SQLCODE, 'Erro de conversao de tipos de dados.');
        RETURN '{"erro": "Erro de conversao de valor"}';

    WHEN OTHERS THEN
        PRC_INSERT_LOG_ERRO('FN_MONTAR_JSON_PET', SQLCODE, SQLERRM);
        RETURN '{"erro": "Falha inesperada ao formatar JSON"}';
END FN_MONTAR_JSON_PET;
/

-- Função 2: Taxa de Adesão com 4 Exceções
CREATE OR REPLACE FUNCTION FN_CALCULAR_TAXA_ADESAO (
    P_ID_MEDICAMENTO IN NUMBER
) RETURN NUMBER
IS
    V_TOTAL_DOSES     NUMBER := 0;
    V_DOSES_TOMADAS   NUMBER := 0;
    V_TAXA_PERCENTUAL NUMBER(5,2) := 0;
    V_EXISTE_MED      NUMBER := 0;
    
    EX_MEDICAMENTO_INEXISTENTE EXCEPTION;
    EX_SEM_DOSES_REGISTRADAS   EXCEPTION;
BEGIN
    SELECT COUNT(1) INTO V_EXISTE_MED 
    FROM TB_MEDICAMENTO 
    WHERE ID_MEDICAMENTO = P_ID_MEDICAMENTO;

    IF V_EXISTE_MED = 0 THEN
        RAISE EX_MEDICAMENTO_INEXISTENTE;
    END IF;

    SELECT 
        COUNT(1),
        COUNT(CASE WHEN ST_TOMOU = 'S' THEN 1 END)
    INTO 
        V_TOTAL_DOSES,
        V_DOSES_TOMADAS
    FROM TB_ADESAO_MEDICAMENTO
    WHERE ID_MEDICAMENTO = P_ID_MEDICAMENTO;

    IF V_TOTAL_DOSES = 0 THEN
        RAISE EX_SEM_DOSES_REGISTRADAS;
    END IF;

    V_TAXA_PERCENTUAL := ROUND((V_DOSES_TOMADAS / V_TOTAL_DOSES) * 100, 2);
    RETURN V_TAXA_PERCENTUAL;

EXCEPTION
    WHEN EX_MEDICAMENTO_INEXISTENTE THEN
        PRC_INSERT_LOG_ERRO('FN_CALCULAR_TAXA_ADESAO', -20010, 'Medicamento ID ' || P_ID_MEDICAMENTO || ' nao encontrado.');
        RETURN -1;

    WHEN EX_SEM_DOSES_REGISTRADAS THEN
        PRC_INSERT_LOG_ERRO('FN_CALCULAR_TAXA_ADESAO', -20011, 'Nenhuma dose registrada para o medicamento ID ' || P_ID_MEDICAMENTO);
        RETURN 0;

    WHEN ZERO_DIVIDE THEN
        PRC_INSERT_LOG_ERRO('FN_CALCULAR_TAXA_ADESAO', SQLCODE, 'Divisao por zero na taxa de adesao.');
        RETURN 0;

    WHEN OTHERS THEN
        PRC_INSERT_LOG_ERRO('FN_CALCULAR_TAXA_ADESAO', SQLCODE, SQLERRM);
        RETURN -99;
END FN_CALCULAR_TAXA_ADESAO;
/

-- Procedimento 1: JOIN Relacional com Saída JSON
CREATE OR REPLACE PROCEDURE PRC_LISTAR_PETS_JSON (
    P_DS_ESPECIE IN VARCHAR2 DEFAULT NULL
)
IS
    CURSOR C_PETS IS
        SELECT 
            P.ID_PET,
            P.NM_PET,
            P.DS_ESPECIE,
            P.DS_RACA,
            P.NR_PESO_KG,
            T.NM_TUTOR,
            C.NM_CLINICA
        FROM TB_PET P
        INNER JOIN TB_TUTOR T   ON T.ID_TUTOR = P.ID_TUTOR
        INNER JOIN TB_CLINICA C ON C.ID_CLINICA = P.ID_CLINICA
        WHERE (P_DS_ESPECIE IS NULL OR UPPER(P.DS_ESPECIE) = UPPER(P_DS_ESPECIE))
        ORDER BY P.ID_PET;

    V_JSON_GERADO  VARCHAR2(4000);
    V_TOTAL_LINHAS NUMBER := 0;
    
    EX_NENHUM_REGISTRO    EXCEPTION;
    EX_PARAMETRO_INVALIDO EXCEPTION;
BEGIN
    IF P_DS_ESPECIE IS NOT NULL AND LENGTH(TRIM(P_DS_ESPECIE)) < 2 THEN
        RAISE EX_PARAMETRO_INVALIDO;
    END IF;

    DBMS_OUTPUT.PUT_LINE('================================================================================');
    DBMS_OUTPUT.PUT_LINE('LISTAGEM DE PETS EM FORMATO JSON (GERAÇÃO MANUAL VIA FN_MONTAR_JSON_PET)');
    DBMS_OUTPUT.PUT_LINE('================================================================================');

    FOR REG IN C_PETS LOOP
        V_TOTAL_LINHAS := V_TOTAL_LINHAS + 1;
        
        V_JSON_GERADO := FN_MONTAR_JSON_PET(
            REG.ID_PET,
            REG.NM_PET,
            REG.DS_ESPECIE,
            REG.DS_RACA,
            REG.NR_PESO_KG,
            REG.NM_TUTOR,
            REG.NM_CLINICA
        );
        
        DBMS_OUTPUT.PUT_LINE(V_JSON_GERADO);
    END LOOP;

    IF V_TOTAL_LINHAS = 0 THEN
        RAISE EX_NENHUM_REGISTRO;
    END IF;

    DBMS_OUTPUT.PUT_LINE('--------------------------------------------------------------------------------');
    DBMS_OUTPUT.PUT_LINE('Total de registros processados: ' || V_TOTAL_LINHAS);

EXCEPTION
    WHEN EX_PARAMETRO_INVALIDO THEN
        PRC_INSERT_LOG_ERRO('PRC_LISTAR_PETS_JSON', -20020, 'Filtro de espécie inválido ou muito curto.');
        DBMS_OUTPUT.PUT_LINE('[EXCEÇÃO TRATADA]: Filtro de espécie fornecido é inválido.');

    WHEN EX_NENHUM_REGISTRO THEN
        PRC_INSERT_LOG_ERRO('PRC_LISTAR_PETS_JSON', -20021, 'Nenhum pet encontrado para os critérios informados.');
        DBMS_OUTPUT.PUT_LINE('[EXCEÇÃO TRATADA]: Nenhum registro encontrado na consulta.');

    WHEN NO_DATA_FOUND THEN
        PRC_INSERT_LOG_ERRO('PRC_LISTAR_PETS_JSON', SQLCODE, 'Dados não encontrados.');
        DBMS_OUTPUT.PUT_LINE('[EXCEÇÃO TRATADA]: Sem dados disponíveis.');

    WHEN OTHERS THEN
        PRC_INSERT_LOG_ERRO('PRC_LISTAR_PETS_JSON', SQLCODE, SQLERRM);
        DBMS_OUTPUT.PUT_LINE('[EXCEÇÃO TRATADA]: Erro inesperado: ' || SQLERRM);
END PRC_LISTAR_PETS_JSON;
/

-- Procedimento 2: Relatório com Subtotais e Total Geral
CREATE OR REPLACE PROCEDURE PRC_RELATORIO_SUBTOTAIS_MANUAL
IS
    CURSOR C_FATOS IS
        SELECT 
            C.NM_CLINICA AS CATEGORIA_1,
            P.NM_PET     AS CATEGORIA_2,
            NVL(CL.NR_ATIVIDADE, 0) AS VALOR_NUMERICO
        FROM TB_COLLAR_LEITURA CL
        INNER JOIN TB_PET P     ON P.ID_PET = CL.ID_PET
        INNER JOIN TB_CLINICA C ON C.ID_CLINICA = P.ID_CLINICA
        ORDER BY C.NM_CLINICA, P.NM_PET;

    V_CAT1_ANTERIOR   TB_CLINICA.NM_CLINICA%TYPE := NULL;
    V_SUBTOTAL_CAT1   NUMBER(12,2) := 0;
    V_TOTAL_GERAL     NUMBER(12,2) := 0;
    V_TOTAL_LINHAS    NUMBER := 0;
    V_PRIMEIRA_LINHA  BOOLEAN := TRUE;

    EX_SEM_DADOS_FATOS EXCEPTION;
    EX_VALOR_NEGATIVO  EXCEPTION;
BEGIN
    DBMS_OUTPUT.PUT_LINE(RPAD('Clinica', 35) || ' ' || RPAD('Pet', 20) || ' ' || LPAD('Atividade', 12));
    DBMS_OUTPUT.PUT_LINE(RPAD('-', 35, '-') || ' ' || RPAD('-', 20, '-') || ' ' || LPAD('-', 12, '-'));

    FOR REG IN C_FATOS LOOP
        V_TOTAL_LINHAS := V_TOTAL_LINHAS + 1;

        IF REG.VALOR_NUMERICO < 0 THEN
            RAISE EX_VALOR_NEGATIVO;
        END IF;

        IF NOT V_PRIMEIRA_LINHA AND REG.CATEGORIA_1 <> V_CAT1_ANTERIOR THEN
            DBMS_OUTPUT.PUT_LINE(RPAD('Sub Total', 56) || ' ' || LPAD(TO_CHAR(V_SUBTOTAL_CAT1, 'FM999990.00'), 12));
            V_SUBTOTAL_CAT1 := 0;
        END IF;

        DBMS_OUTPUT.PUT_LINE(
            RPAD(REG.CATEGORIA_1, 35) || ' ' ||
            RPAD(REG.CATEGORIA_2, 20) || ' ' ||
            LPAD(TO_CHAR(REG.VALOR_NUMERICO, 'FM999990.00'), 12)
        );

        V_SUBTOTAL_CAT1 := V_SUBTOTAL_CAT1 + REG.VALOR_NUMERICO;
        V_TOTAL_GERAL   := V_TOTAL_GERAL + REG.VALOR_NUMERICO;
        V_CAT1_ANTERIOR := REG.CATEGORIA_1;
        V_PRIMEIRA_LINHA := FALSE;
    END LOOP;

    IF V_TOTAL_LINHAS = 0 THEN
        RAISE EX_SEM_DADOS_FATOS;
    END IF;

    DBMS_OUTPUT.PUT_LINE(RPAD('Sub Total', 56) || ' ' || LPAD(TO_CHAR(V_SUBTOTAL_CAT1, 'FM999990.00'), 12));
    DBMS_OUTPUT.PUT_LINE(RPAD('Total Geral', 56) || ' ' || LPAD(TO_CHAR(V_TOTAL_GERAL, 'FM999990.00'), 12));

EXCEPTION
    WHEN EX_SEM_DADOS_FATOS THEN
        PRC_INSERT_LOG_ERRO('PRC_RELATORIO_SUBTOTAIS_MANUAL', -20030, 'Sem dados para sumarização.');
        DBMS_OUTPUT.PUT_LINE('[EXCEÇÃO TRATADA]: Não há registros suficientes.');

    WHEN EX_VALOR_NEGATIVO THEN
        PRC_INSERT_LOG_ERRO('PRC_RELATORIO_SUBTOTAIS_MANUAL', -20031, 'Valor numérico inconsistente.');
        DBMS_OUTPUT.PUT_LINE('[EXCEÇÃO TRATADA]: Valor numérico inválido encontrado.');

    WHEN VALUE_ERROR THEN
        PRC_INSERT_LOG_ERRO('PRC_RELATORIO_SUBTOTAIS_MANUAL', SQLCODE, 'Erro de conversão numérica.');
        DBMS_OUTPUT.PUT_LINE('[EXCEÇÃO TRATADA]: Erro na conversão numérica de subtotais.');

    WHEN OTHERS THEN
        PRC_INSERT_LOG_ERRO('PRC_RELATORIO_SUBTOTAIS_MANUAL', SQLCODE, SQLERRM);
        DBMS_OUTPUT.PUT_LINE('[EXCEÇÃO TRATADA]: Falha durante a execução: ' || SQLERRM);
END PRC_RELATORIO_SUBTOTAIS_MANUAL;
/